//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SentToMIGULDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class fn_billing
    {
        public string billing_id { get; set; }
        public string billing_type { get; set; }
        public System.DateTime transaction_date { get; set; }
        public string book_code { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public System.DateTime due_date { get; set; }
        public string desc { get; set; }
        public string application_no { get; set; }
        public string currency_code { get; set; }
        public decimal exchange_rate { get; set; }
        public Nullable<decimal> exchange_rate_tax { get; set; }
        public decimal amount { get; set; }
        public decimal amountc { get; set; }
        public string tpa_code { get; set; }
        public string provider_code { get; set; }
        public string reinsurer_id { get; set; }
        public string intermediary_code { get; set; }
        public string company_id { get; set; }
        public string billing_name { get; set; }
        public string billing_address { get; set; }
        public string payment_method_code { get; set; }
        public string bank_code { get; set; }
        public string account_no { get; set; }
        public string account_holder { get; set; }
        public string stamp_status { get; set; }
        public Nullable<System.DateTime> stamp_date { get; set; }
        public Nullable<decimal> stamp_amount { get; set; }
        public Nullable<decimal> stamp_amountc { get; set; }
        public string stamp_pointer_id { get; set; }
        public string stamp_reff_id { get; set; }
        public string approval_status { get; set; }
        public Nullable<System.DateTime> approval_date { get; set; }
        public string approval_userid { get; set; }
        public string approval_pointer_id { get; set; }
        public string approval_reff_id { get; set; }
        public string cancel_status { get; set; }
        public Nullable<System.DateTime> cancel_date { get; set; }
        public string cancel_userid { get; set; }
        public string cancel_pointer_id { get; set; }
        public string cancel_reff_id { get; set; }
        public string recon_status { get; set; }
        public Nullable<System.DateTime> recon_date { get; set; }
        public string recon_userid { get; set; }
        public Nullable<decimal> recon_amount { get; set; }
        public Nullable<decimal> recon_amountc { get; set; }
        public string recon_pointer_id { get; set; }
        public string recon_reff_id { get; set; }
        public string print_status { get; set; }
        public Nullable<System.DateTime> print_date { get; set; }
        public Nullable<decimal> print_counter { get; set; }
        public string print_userid { get; set; }
        public string recuring_status { get; set; }
        public Nullable<System.DateTime> recuring_date { get; set; }
        public string recuring_userid { get; set; }
        public string recuring_pointer_id { get; set; }
        public string recuring_reff_id { get; set; }
        public string recuring_file_name { get; set; }
        public System.DateTime create_date { get; set; }
        public string create_id { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public string modify_id { get; set; }
        public string prop_id { get; set; }
        public string offset_status { get; set; }
        public Nullable<System.DateTime> offset_date { get; set; }
        public string offset_userid { get; set; }
        public string offset_pointer_id { get; set; }
        public string offset_reff_id { get; set; }
        public string receipt_status { get; set; }
        public Nullable<System.DateTime> receipt_date { get; set; }
        public Nullable<decimal> receipt_counter { get; set; }
        public string receipt_userid { get; set; }
        public string subsidiary_id { get; set; }
        public string office_code { get; set; }
        public string channel_code { get; set; }
        public string letter_no { get; set; }
        public string cancel_desc { get; set; }
        public string policy_no { get; set; }
        public string pointer_id { get; set; }
        public string voucher_reff_id { get; set; }
        public string tax23_status { get; set; }
        public string recon_tax23_status { get; set; }
        public Nullable<System.DateTime> recon_tax23_date { get; set; }
        public Nullable<decimal> recon_tax23_amount { get; set; }
        public Nullable<decimal> recon_tax23_amountc { get; set; }
        public string recon_tax23_userid { get; set; }
        public string recon_tax23_pointer_id { get; set; }
        public string recon_tax23_reff_id { get; set; }
        public string voucher_tax23_reff_id { get; set; }
        public Nullable<decimal> tax23 { get; set; }
        public Nullable<decimal> tax23c { get; set; }
        public Nullable<decimal> policy_amount { get; set; }
        public Nullable<decimal> policy_amountc { get; set; }
        public Nullable<decimal> recon_policy_amount { get; set; }
        public Nullable<decimal> recon_policy_amountc { get; set; }
        public Nullable<decimal> recon_stamp_amount { get; set; }
        public Nullable<decimal> recon_stamp_amountc { get; set; }
        public string signer_name { get; set; }
        public string signer_level { get; set; }
        public string signer_position { get; set; }
        public string kanpen_status { get; set; }
        public Nullable<System.DateTime> kanpen_date { get; set; }
        public string kanpen_userid { get; set; }
        public string kanpus_book_code { get; set; }
        public string kanpus_status { get; set; }
        public Nullable<System.DateTime> kanpus_date { get; set; }
        public string kanpus_userid { get; set; }
        public string kanpus_pointer_id { get; set; }
        public string kanpus_reff_id { get; set; }
        public string endors_id { get; set; }
        public string alteration_id { get; set; }
        public string main_billing { get; set; }
        public int installment { get; set; }
        public string saving_status { get; set; }
        public Nullable<decimal> saving_initial { get; set; }
        public Nullable<decimal> saving_initialc { get; set; }
        public Nullable<decimal> saving_initial_comm { get; set; }
        public Nullable<decimal> saving_initial_commc { get; set; }
        public Nullable<int> saving_initial_installment { get; set; }
        public Nullable<decimal> saving_regular { get; set; }
        public Nullable<decimal> saving_regularc { get; set; }
        public Nullable<decimal> saving_regular_comm { get; set; }
        public Nullable<decimal> saving_regular_commc { get; set; }
        public Nullable<int> saving_regular_installment { get; set; }
        public string recon_saving_status { get; set; }
        public Nullable<System.DateTime> recon_saving_date { get; set; }
        public Nullable<decimal> recon_saving_amount { get; set; }
        public string recon_saving_userid { get; set; }
        public string recon_saving_pointer_id { get; set; }
        public string recon_saving_reff_id { get; set; }
        public string virtual_account_no { get; set; }
        public string virtual_account_prefix { get; set; }
        public string payment_mode_code { get; set; }
        public string installment_total { get; set; }
        public string package_code { get; set; }
        public string download_status { get; set; }
        public Nullable<System.DateTime> download_date { get; set; }
        public string download_userid { get; set; }
        public string accrual_voucher_id { get; set; }
        public Nullable<System.DateTime> accrual_date { get; set; }
        public string accrual_userid { get; set; }
        public string va_status { get; set; }
        public string va_status_userid { get; set; }
        public Nullable<System.DateTime> va_status_date { get; set; }
        public string periode { get; set; }
        public string tahun { get; set; }
        public string bulan { get; set; }
        public string approval_doc_receive_status { get; set; }
        public Nullable<System.DateTime> approval_doc_receive_date { get; set; }
        public string approval_doc_receive_userid { get; set; }
        public string cancel_doc_receive_status { get; set; }
        public Nullable<System.DateTime> cancel_doc_receive_date { get; set; }
        public string cancel_doc_receive_userid { get; set; }
        public string approval_doc_complete_status { get; set; }
        public Nullable<System.DateTime> approval_doc_complete_date { get; set; }
        public string approval_doc_complete_userid { get; set; }
        public string cancel_doc_complete_status { get; set; }
        public Nullable<System.DateTime> cancel_doc_complete_date { get; set; }
        public string cancel_doc_complete_userid { get; set; }
        public string approval_doc_manager_status { get; set; }
        public Nullable<System.DateTime> approval_doc_manager_date { get; set; }
        public string approval_doc_manager_userid { get; set; }
        public string cancel_doc_manager_status { get; set; }
        public Nullable<System.DateTime> cancel_doc_manager_date { get; set; }
        public string cancel_doc_manager_userid { get; set; }
        public Nullable<decimal> bank_charge { get; set; }
    }
}
