//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SentToMIGULDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class fn_collection
    {
        public string collection_id { get; set; }
        public System.DateTime collection_date { get; set; }
        public string rk_status { get; set; }
        public System.DateTime transaction_date { get; set; }
        public string desc { get; set; }
        public string application_no { get; set; }
        public string tpa_code { get; set; }
        public string provider_code { get; set; }
        public string reinsurer_id { get; set; }
        public string intermediary_code { get; set; }
        public string book_code { get; set; }
        public string currency_code { get; set; }
        public Nullable<decimal> exchange_rate { get; set; }
        public Nullable<decimal> exchange_rate_tax { get; set; }
        public decimal amount { get; set; }
        public decimal amountc { get; set; }
        public Nullable<decimal> amount_forex { get; set; }
        public Nullable<decimal> vat { get; set; }
        public Nullable<decimal> vatc { get; set; }
        public Nullable<decimal> vat_forex { get; set; }
        public Nullable<decimal> tax23 { get; set; }
        public Nullable<decimal> tax23c { get; set; }
        public Nullable<decimal> tax23_forex { get; set; }
        public Nullable<decimal> tolerance { get; set; }
        public Nullable<decimal> tolerancec { get; set; }
        public Nullable<decimal> bank_charge { get; set; }
        public Nullable<decimal> bank_chargec { get; set; }
        public Nullable<decimal> stamp_amount { get; set; }
        public Nullable<decimal> stamp_amountc { get; set; }
        public string payment_method_code { get; set; }
        public string giro_no { get; set; }
        public string giro_status { get; set; }
        public Nullable<System.DateTime> giro_date { get; set; }
        public string giro_userid { get; set; }
        public Nullable<System.DateTime> rk_date_estimate { get; set; }
        public System.DateTime rk_date { get; set; }
        public string bank_code { get; set; }
        public string account_no { get; set; }
        public string account_holder { get; set; }
        public string approval_status { get; set; }
        public Nullable<System.DateTime> approval_date { get; set; }
        public string approval_userid { get; set; }
        public string approval_pointer_id { get; set; }
        public string approval_reff_id { get; set; }
        public string cancel_status { get; set; }
        public Nullable<System.DateTime> cancel_date { get; set; }
        public string cancel_userid { get; set; }
        public string cancel_pointer_id { get; set; }
        public string cancel_reff_id { get; set; }
        public string recon_status { get; set; }
        public Nullable<System.DateTime> recon_date { get; set; }
        public string recon_userid { get; set; }
        public Nullable<decimal> recon_amount { get; set; }
        public Nullable<decimal> recon_amountc { get; set; }
        public string recon_pointer_id { get; set; }
        public string recon_reff_id { get; set; }
        public string print_status { get; set; }
        public Nullable<System.DateTime> print_date { get; set; }
        public Nullable<decimal> print_counter { get; set; }
        public string print_userid { get; set; }
        public string upload_id { get; set; }
        public System.DateTime create_date { get; set; }
        public string create_id { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public string modify_id { get; set; }
        public Nullable<decimal> discount_amount { get; set; }
        public Nullable<decimal> discount_amountc { get; set; }
        public Nullable<decimal> discount_amount_forex { get; set; }
        public Nullable<decimal> comm_amount { get; set; }
        public Nullable<decimal> comm_amountc { get; set; }
        public Nullable<decimal> comm_amount_forex { get; set; }
        public string office_code { get; set; }
        public string cancel_desc { get; set; }
        public string policy_no { get; set; }
        public string voucher_pointer_id { get; set; }
        public string voucher_reff_id { get; set; }
        public string tax23_status { get; set; }
        public string claim_id { get; set; }
        public string absorb_status { get; set; }
        public Nullable<System.DateTime> absorb_date { get; set; }
        public string absorb_userid { get; set; }
        public Nullable<decimal> absorb_amount { get; set; }
        public Nullable<decimal> policy_amount { get; set; }
        public Nullable<decimal> policy_amountc { get; set; }
        public string signer_name { get; set; }
        public string signer_level { get; set; }
        public string signer_position { get; set; }
        public string participant_status { get; set; }
        public string saku_code { get; set; }
        public string saving_status { get; set; }
        public string breakup_status { get; set; }
        public string virtual_account_no { get; set; }
        public string no_crv { get; set; }
        public string finance_no { get; set; }
    }
}
