//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SentToMIGULDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MIGULDBDevEntities : DbContext
    {
        public MIGULDBDevEntities()
            : base("name=MIGULDBDevEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cd_client_> cd_client_ { get; set; }
        public virtual DbSet<fn_fundnav_> fn_fundnav_ { get; set; }
        public virtual DbSet<OldClientIdToNewClientId> OldClientIdToNewClientId { get; set; }
        public virtual DbSet<ps_fund_transaction_history_> ps_fund_transaction_history_ { get; set; }
    }
}
