//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SentToMIGULDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ps_alteration
    {
        public string alteration_id { get; set; }
        public string alteration_month { get; set; }
        public int alteration_no { get; set; }
        public string alteration_type_code { get; set; }
        public string application_no { get; set; }
        public string endors_no { get; set; }
        public System.DateTime alteration_date { get; set; }
        public string reference_no { get; set; }
        public System.DateTime reference_date { get; set; }
        public string alteration_desc { get; set; }
        public string alteration_status { get; set; }
        public System.DateTime effective_date { get; set; }
        public Nullable<System.DateTime> status_date { get; set; }
        public string approval_status { get; set; }
        public Nullable<System.DateTime> approval_date { get; set; }
        public string approval_id { get; set; }
        public Nullable<decimal> print_count { get; set; }
        public Nullable<System.DateTime> collection_date { get; set; }
        public string investible_status { get; set; }
        public Nullable<System.DateTime> pricing_date { get; set; }
        public Nullable<System.DateTime> posting_date { get; set; }
        public string posting_status { get; set; }
        public Nullable<System.DateTime> print_date { get; set; }
        public Nullable<System.DateTime> addendum_shipping_date { get; set; }
        public string addendum_shipping_office { get; set; }
        public Nullable<System.DateTime> addendum_receive_date { get; set; }
    }
}
