//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SentToMIGULDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class sw_city
    {
        public string city_code { get; set; }
        public string province_code { get; set; }
        public string city_name { get; set; }
        public string st_active { get; set; }
        public string remark { get; set; }
        public string st_publish { get; set; }
        public int order_num { get; set; }
        public string create_id { get; set; }
        public System.DateTime create_date { get; set; }
        public string modify_id { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
    }
}
