//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SentToMIGULDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class sw_identity_type
    {
        public string id_type_code { get; set; }
        public string id_type_name { get; set; }
    }
}
