//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SentToMIGULDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class sw_office
    {
        public string office_code { get; set; }
        public string parent_office_code { get; set; }
        public string regional_code { get; set; }
        public string office_type_code { get; set; }
        public string area_code { get; set; }
        public string office_name { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string city { get; set; }
        public string postal_code { get; set; }
        public string phone_no { get; set; }
        public string fax_no { get; set; }
        public string office_head { get; set; }
        public string create_id { get; set; }
        public System.DateTime create_date { get; set; }
        public string modify_id { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public string office_full_name { get; set; }
        public string office_commercial_name { get; set; }
        public string default_status { get; set; }
        public string email { get; set; }
        public string website { get; set; }
        public string city_code { get; set; }
        public string cs_phone { get; set; }
        public byte[] logo { get; set; }
    }
}
