//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMigrationConsoleTools.DataModels.PLDataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class acc_bank_bi
    {
        public string kode_bi { get; set; }
        public string nama_bank_bi { get; set; }
        public System.DateTime tgl_rekam { get; set; }
        public string petugas_rekam { get; set; }
        public Nullable<System.DateTime> tgl_ubah { get; set; }
        public string petugas_ubah { get; set; }
        public string kode_kliring { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
    }
}
