//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMigrationConsoleTools.DataModels.PLDataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class fn_bank_bi
    {
        public string bi_code { get; set; }
        public string bi_name { get; set; }
        public string clearance_code { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public string abbreviation { get; set; }
        public string virtual_account_prefix { get; set; }
        public Nullable<int> min_digit_account_no { get; set; }
        public Nullable<int> max_digit_account_no { get; set; }
        public System.DateTime create_date { get; set; }
        public string create_id { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public string modify_id { get; set; }
        public string swift_code { get; set; }
    }
}
