//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMigrationConsoleTools.DataModels.PLDataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class fn_collection_detail
    {
        public string collection_id { get; set; }
        public string billing_id { get; set; }
        public System.DateTime transaction_date { get; set; }
        public System.DateTime due_date { get; set; }
        public string currency_code { get; set; }
        public Nullable<decimal> exchange_rate { get; set; }
        public decimal collection_amount { get; set; }
        public decimal collection_amountc { get; set; }
        public decimal billing_amount { get; set; }
        public decimal billing_amountc { get; set; }
        public Nullable<decimal> amount_forex { get; set; }
        public Nullable<decimal> vat { get; set; }
        public Nullable<decimal> vatc { get; set; }
        public Nullable<decimal> vat_forex { get; set; }
        public Nullable<decimal> tax23 { get; set; }
        public Nullable<decimal> tax23c { get; set; }
        public Nullable<decimal> tax23_forex { get; set; }
        public Nullable<decimal> tolerance { get; set; }
        public Nullable<decimal> tolerancec { get; set; }
        public Nullable<decimal> bank_charge { get; set; }
        public Nullable<decimal> bank_chargec { get; set; }
        public Nullable<decimal> stamp_amount { get; set; }
        public Nullable<decimal> stamp_amountc { get; set; }
        public string cancel_status { get; set; }
        public Nullable<System.DateTime> cancel_date { get; set; }
        public string cancel_userid { get; set; }
        public string recon_status { get; set; }
        public Nullable<System.DateTime> recon_date { get; set; }
        public string recon_userid { get; set; }
        public System.DateTime create_date { get; set; }
        public string create_id { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public string modify_id { get; set; }
        public Nullable<decimal> discount_amount { get; set; }
        public Nullable<decimal> discount_amountc { get; set; }
        public Nullable<decimal> discount_amount_forex { get; set; }
        public Nullable<decimal> comm_amount { get; set; }
        public Nullable<decimal> comm_amountc { get; set; }
        public Nullable<decimal> comm_amount_forex { get; set; }
        public Nullable<decimal> exchange_rate_tax { get; set; }
        public string pointer_id { get; set; }
        public Nullable<decimal> exchange_rate_final { get; set; }
        public string approval_status { get; set; }
        public Nullable<System.DateTime> approval_date { get; set; }
        public string approval_userid { get; set; }
        public Nullable<decimal> saving_amount { get; set; }
        public Nullable<decimal> saving_amountc { get; set; }
        public string recon_saving_status { get; set; }
        public Nullable<System.DateTime> recon_saving_date { get; set; }
        public string recon_saving_userid { get; set; }
    }
}
