//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMigrationConsoleTools.DataModels.PLDataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class fn_disbursement_detail
    {
        public string disbursement_id { get; set; }
        public string billing_id { get; set; }
        public System.DateTime transaction_date { get; set; }
        public Nullable<System.DateTime> due_date { get; set; }
        public Nullable<System.DateTime> billing_date { get; set; }
        public string currency_code { get; set; }
        public Nullable<decimal> exchange_rate { get; set; }
        public decimal disbursement_amount { get; set; }
        public string pointer_id { get; set; }
    }
}
