//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMigrationConsoleTools.DataModels.PLDataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class fn_debitnote
    {
        public string debitnote_id { get; set; }
        public string debitnote_type { get; set; }
        public string pointer_id { get; set; }
        public string application_no { get; set; }
        public string alteration_id { get; set; }
        public string reff_pointer_id { get; set; }
        public System.DateTime transaction_date { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime end_date { get; set; }
        public System.DateTime due_date { get; set; }
        public string desc { get; set; }
        public string currency_code { get; set; }
        public decimal exchange_rate { get; set; }
        public decimal exchange_rate_tax { get; set; }
        public decimal amount { get; set; }
        public Nullable<decimal> amountc { get; set; }
        public Nullable<decimal> amount_forex { get; set; }
        public Nullable<decimal> discount_amount { get; set; }
        public Nullable<decimal> discount_amountc { get; set; }
        public Nullable<decimal> discount_amount_forex { get; set; }
        public Nullable<decimal> comm_amount { get; set; }
        public Nullable<decimal> comm_amountc { get; set; }
        public Nullable<decimal> comm_amount_forex { get; set; }
        public Nullable<decimal> tolerance { get; set; }
        public Nullable<decimal> tolerancec { get; set; }
        public Nullable<decimal> vat { get; set; }
        public Nullable<decimal> vatc { get; set; }
        public Nullable<decimal> vat_forex { get; set; }
        public Nullable<decimal> tax23 { get; set; }
        public Nullable<decimal> tax23c { get; set; }
        public Nullable<decimal> tax23_forex { get; set; }
        public Nullable<decimal> stamp { get; set; }
        public Nullable<decimal> stampc { get; set; }
        public string approval_status { get; set; }
        public Nullable<System.DateTime> approval_date { get; set; }
        public string approval_userid { get; set; }
        public string approval_pointer_id { get; set; }
        public string approval_reff_id { get; set; }
        public string cancel_status { get; set; }
        public Nullable<System.DateTime> cancel_date { get; set; }
        public string cancel_userid { get; set; }
        public string cancel_pointer_id { get; set; }
        public string cancel_reff_id { get; set; }
        public string offset_status { get; set; }
        public System.DateTime offset_date { get; set; }
        public string offset_userid { get; set; }
        public string offset_pointer_id { get; set; }
        public string offset_reff_id { get; set; }
        public string recon_status { get; set; }
        public Nullable<System.DateTime> recon_date { get; set; }
        public Nullable<decimal> recon_amount { get; set; }
        public Nullable<decimal> recon_amountc { get; set; }
        public string recon_userid { get; set; }
        public string recon_pointer_id { get; set; }
        public string recon_reff_id { get; set; }
        public System.DateTime create_date { get; set; }
        public string create_id { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public string modify_id { get; set; }
        public string prop_id { get; set; }
        public string subsidiary_id { get; set; }
        public string office_code { get; set; }
        public string channel_code { get; set; }
        public string policy_no { get; set; }
        public string main_debitnote { get; set; }
        public string product_code { get; set; }
        public int tahun_kep { get; set; }
        public string tax23_status { get; set; }
        public string recon_tax23_status { get; set; }
        public Nullable<System.DateTime> recon_tax23_date { get; set; }
        public Nullable<decimal> recon_tax23_amount { get; set; }
        public Nullable<decimal> recon_tax23_amountc { get; set; }
        public string recon_tax23_userid { get; set; }
        public string recon_tax23_pointer_id { get; set; }
        public string recon_tax23_reff_id { get; set; }
        public string voucher_reff_id { get; set; }
        public string voucher_tax23_reff_id { get; set; }
        public string intermediary_code { get; set; }
        public Nullable<decimal> policy_amount { get; set; }
        public Nullable<decimal> policy_amountc { get; set; }
        public Nullable<int> installment { get; set; }
        public string saving_status { get; set; }
        public Nullable<decimal> saving_initial { get; set; }
        public Nullable<decimal> saving_initialc { get; set; }
        public Nullable<decimal> saving_initial_comm { get; set; }
        public Nullable<decimal> saving_initial_commc { get; set; }
        public Nullable<int> saving_initial_installment { get; set; }
        public Nullable<decimal> saving_regular { get; set; }
        public Nullable<decimal> saving_regularc { get; set; }
        public Nullable<decimal> saving_regular_comm { get; set; }
        public Nullable<decimal> saving_regular_commc { get; set; }
        public Nullable<int> saving_regular_installment { get; set; }
        public string recon_saving_status { get; set; }
        public Nullable<System.DateTime> recon_saving_date { get; set; }
        public Nullable<decimal> recon_saving_amount { get; set; }
        public string recon_saving_userid { get; set; }
        public string recon_saving_pointer_id { get; set; }
        public string recon_saving_reff_id { get; set; }
        public string package_code { get; set; }
    }
}
