//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMigrationConsoleTools.DataModels.PLDataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class fn_disbursement
    {
        public string disbursement_id { get; set; }
        public System.DateTime disbursement_date { get; set; }
        public System.DateTime transaction_date { get; set; }
        public string book_code { get; set; }
        public string currency_code { get; set; }
        public decimal exchange_rate { get; set; }
        public decimal amount { get; set; }
        public Nullable<decimal> bank_charge { get; set; }
        public string bank_code { get; set; }
        public string account_no { get; set; }
        public string account_holder { get; set; }
        public string office_code { get; set; }
        public string policy_no { get; set; }
        public Nullable<decimal> stamp_amount { get; set; }
        public string no_cdv { get; set; }
        public string no_finance { get; set; }
    }
}
