//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMigrationConsoleTools.DataModels.PLDataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class nb_application
    {
        public string application_no { get; set; }
        public string form_no { get; set; }
        public System.DateTime apply_date { get; set; }
        public string package_code { get; set; }
        public string product_code { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime end_date { get; set; }
        public System.DateTime premium_end_date { get; set; }
        public decimal premium_period_year { get; set; }
        public Nullable<decimal> premium_period_month { get; set; }
        public string payment_mode_code { get; set; }
        public string payment_frequency_code { get; set; }
        public string currency_code { get; set; }
        public string policy_holder_no { get; set; }
        public string premium_payor_no { get; set; }
        public string insured_no { get; set; }
        public string insurable_type_code { get; set; }
        public string spouse_no { get; set; }
        public string parent_no { get; set; }
        public string intermediary_code { get; set; }
        public string agent_servicing { get; set; }
        public string introducer_no { get; set; }
        public string office_code { get; set; }
        public Nullable<decimal> age_year { get; set; }
        public Nullable<decimal> age_month { get; set; }
        public Nullable<decimal> regular_premium { get; set; }
        public Nullable<decimal> regular_topup { get; set; }
        public Nullable<decimal> single_topup { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
        public Nullable<System.DateTime> pricing_date { get; set; }
        public Nullable<System.DateTime> posting_date { get; set; }
        public decimal exchange_rate { get; set; }
        public string payment_method_code { get; set; }
        public string application_status { get; set; }
        public System.DateTime receive_date { get; set; }
        public string medical_status { get; set; }
        public string channel_code { get; set; }
        public Nullable<decimal> height { get; set; }
        public Nullable<decimal> weight { get; set; }
        public string freelookup_status { get; set; }
        public string virtual_account_no { get; set; }
        public Nullable<System.DateTime> card_expire_date { get; set; }
        public string card_holder_name { get; set; }
        public string user_checker { get; set; }
        public string notification_email { get; set; }
        public string policy_no { get; set; }
        public string notification_mobile { get; set; }
        public string policy_status { get; set; }
        public System.DateTime policy_status_date { get; set; }
        public string convert_status { get; set; }
        public Nullable<System.DateTime> convert_date { get; set; }
        public string convert_userid { get; set; }
        public string approval_status { get; set; }
        public Nullable<System.DateTime> approval_date { get; set; }
        public string approval_userid { get; set; }
        public string card_type { get; set; }
        public string card_no { get; set; }
        public Nullable<System.DateTime> premium_holiday_start { get; set; }
        public Nullable<System.DateTime> premium_holiday_end { get; set; }
        public Nullable<System.DateTime> policy_shipping_date { get; set; }
        public Nullable<System.DateTime> policy_receive_date { get; set; }
        public string policy_shipping_office { get; set; }
        public string agent_servicing_old { get; set; }
        public Nullable<System.DateTime> interest_period_start_date { get; set; }
        public Nullable<System.DateTime> interest_period_end_date { get; set; }
        public string intermediary_code_reff { get; set; }
        public string fac_status { get; set; }
        public string agency_team_code { get; set; }
        public Nullable<decimal> mti_period_month { get; set; }
    }
}
