//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMigrationConsoleTools.DataModels.PLDataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class nb_application_mgi
    {
        public string application_no { get; set; }
        public System.DateTime mgi_start_date { get; set; }
        public System.DateTime mgi_end_date { get; set; }
        public int no_aro { get; set; }
        public Nullable<decimal> premium_amount { get; set; }
        public Nullable<decimal> investment_amount { get; set; }
        public Nullable<decimal> premi_ro_amount { get; set; }
        public Nullable<decimal> unit_ro_rp { get; set; }
        public Nullable<decimal> unit_ro_stu { get; set; }
        public Nullable<decimal> interest_rate { get; set; }
        public Nullable<decimal> sum_assured { get; set; }
        public Nullable<int> total_days { get; set; }
        public Nullable<int> day_in_year { get; set; }
        public Nullable<decimal> period_mgi { get; set; }
        public Nullable<System.DateTime> aro_process_date { get; set; }
        public string aro_process_status { get; set; }
        public string aro_type { get; set; }
        public Nullable<decimal> pnl_unit { get; set; }
        public Nullable<decimal> pnl_amount { get; set; }
        public Nullable<System.DateTime> mgi_next_date { get; set; }
        public Nullable<decimal> default_interest_rate { get; set; }
        public Nullable<decimal> aro_default_interest_rate { get; set; }
        public Nullable<decimal> aro_interest_rate { get; set; }
        public Nullable<decimal> last_unit_amount { get; set; }
        public Nullable<System.DateTime> last_pricing_date { get; set; }
        public Nullable<decimal> last_account_value { get; set; }
        public Nullable<decimal> wd_premium { get; set; }
        public Nullable<decimal> wd_investment { get; set; }
        public Nullable<decimal> wd_premium_ro { get; set; }
        public Nullable<decimal> wd_investment_ro { get; set; }
        public Nullable<decimal> wd_investment_ro_cair { get; set; }
        public Nullable<decimal> wd_bonus { get; set; }
        public Nullable<decimal> management_fee { get; set; }
        public Nullable<decimal> loyalty_bonus_nu { get; set; }
        public Nullable<decimal> loyalty_bonus_u { get; set; }
        public Nullable<decimal> wd_penalty { get; set; }
        public Nullable<decimal> aro_period_mgi { get; set; }
        public string intermediary_code { get; set; }
        public string intermediary_code_reff { get; set; }
        public string agency_team_code { get; set; }
        public string aro_intermediary_code { get; set; }
        public string aro_intermediary_code_reff { get; set; }
        public string aro_agency_team_code { get; set; }
        public Nullable<decimal> sum_assured_modification { get; set; }
        public string age_policy_holder { get; set; }
        public string age_insured { get; set; }
        public Nullable<System.DateTime> pricing_date { get; set; }
        public string posting_status { get; set; }
    }
}
