//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMigrationConsoleTools.DataModels.PLDataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class nb_application_fund
    {
        public string application_no { get; set; }
        public string fund_code { get; set; }
        public decimal allocation_percentage { get; set; }
        public decimal unit_amount { get; set; }
    }
}
