//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMigrationConsoleTools.DataModels.PLDataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ps_alteration_beneficiary
    {
        public string alteration_id { get; set; }
        public string client_no { get; set; }
        public decimal order_no { get; set; }
        public Nullable<decimal> percentage { get; set; }
        public string insurable_type_code { get; set; }
    }
}
