//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMigrationConsoleTools.DataModels.PLDataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ps_alteration_topup
    {
        public string alteration_id { get; set; }
        public string current_fundhouse_code { get; set; }
        public System.DateTime trans_date { get; set; }
        public decimal trans_amount { get; set; }
        public decimal loading_percent { get; set; }
        public decimal loading_amount { get; set; }
        public decimal net_topup_amount { get; set; }
        public Nullable<System.DateTime> settle_date { get; set; }
        public Nullable<System.DateTime> pricing_date { get; set; }
        public string posting_status { get; set; }
        public Nullable<System.DateTime> posting_date { get; set; }
    }
}
