//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMigrationConsoleTools.DataModels.PLDataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class sw_alteration_type
    {
        public string alteration_type_code { get; set; }
        public string alteration_type_name { get; set; }
        public string create_id { get; set; }
        public System.DateTime create_date { get; set; }
        public string modify_id { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public string print_endors_status { get; set; }
        public string unit_link_status { get; set; }
        public Nullable<int> display_order { get; set; }
        public string alteration_type_group { get; set; }
        public string display_invest { get; set; }
    }
}
