//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMigrationConsoleTools.DataModels.PLDataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class sw_provider
    {
        public string provider_code { get; set; }
        public string provider_name { get; set; }
        public string provider_desc { get; set; }
        public string provider_type { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string city_code { get; set; }
        public string province_code { get; set; }
        public string zip_code { get; set; }
        public string country_code { get; set; }
        public string regional_code { get; set; }
        public string phone_no { get; set; }
        public string fax_no { get; set; }
        public string email { get; set; }
        public string website { get; set; }
        public string contact_name { get; set; }
        public string contact_occupation { get; set; }
        public Nullable<decimal> agreement_no { get; set; }
        public Nullable<System.DateTime> agreement_date { get; set; }
        public string cost_mode { get; set; }
        public string status { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime end_date { get; set; }
        public string bank_code { get; set; }
        public string account_no { get; set; }
        public string account_holder { get; set; }
        public System.DateTime create_date { get; set; }
        public string create_id { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public string modify_id { get; set; }
        public string bi_code { get; set; }
        public string bank_branch { get; set; }
        public string bank_city { get; set; }
    }
}
