//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMigrationConsoleTools.DataModels.PLDataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class uw_underwriting
    {
        public string medical_req_no { get; set; }
        public string application_no { get; set; }
        public string insured_no { get; set; }
        public string remark { get; set; }
        public string underwriting_type_code { get; set; }
        public Nullable<System.DateTime> medical_checkup_date { get; set; }
        public string letter_no { get; set; }
        public Nullable<System.DateTime> letter_date { get; set; }
        public string document_complete_status { get; set; }
        public System.DateTime document_complete_date { get; set; }
        public string posting_status { get; set; }
        public Nullable<System.DateTime> posting_date { get; set; }
        public string posting_userid { get; set; }
        public string alteration_id { get; set; }
        public System.DateTime decision_date { get; set; }
    }
}
