//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REAL_Data_Migration_Tool.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BUPRH
    {
        public string PR_Num { get; set; }
        public Nullable<System.DateTime> PR_Date { get; set; }
        public string PR_Produk { get; set; }
        public string PR_Type { get; set; }
        public Nullable<decimal> PR_Amount { get; set; }
        public string PR_Bank { get; set; }
        public string PR_Sts { get; set; }
        public string Create_UserId { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public string Modify_UserId { get; set; }
        public Nullable<System.DateTime> Modify_Date { get; set; }
    }
}
