//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REAL_Data_Migration_Tool.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommonSetting
    {
        public string RefId { get; set; }
        public string RefKey { get; set; }
        public Nullable<decimal> RefValue { get; set; }
        public string Create_UserId { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public string Modify_UserId { get; set; }
        public Nullable<System.DateTime> Modify_Date { get; set; }
    }
}
