//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REAL_Data_Migration_Tool.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class IILTransaction
    {
        public string No_SPAJ { get; set; }
        public Nullable<System.DateTime> Eff_Date { get; set; }
        public System.DateTime Value_Date { get; set; }
        public Nullable<int> Trns_Seq { get; set; }
        public string Trans_Type { get; set; }
        public Nullable<decimal> Trans_Amount { get; set; }
        public Nullable<decimal> NAV { get; set; }
        public Nullable<decimal> Trans_Unit { get; set; }
        public Nullable<decimal> Trans_Balance { get; set; }
        public string Trans_Sts { get; set; }
        public string Create_UserId { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public string Modify_UserId { get; set; }
        public Nullable<System.DateTime> Modify_Date { get; set; }
    }
}
