//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REAL_Data_Migration_Tool.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PolisIPPARO
    {
        public string No_Polis { get; set; }
        public string No_Polis_Old { get; set; }
        public Nullable<System.DateTime> ARO_Date { get; set; }
    }
}
