//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REAL_Data_Migration_Tool.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rate_COI
    {
        public int Age { get; set; }
        public string Sex { get; set; }
        public Nullable<decimal> Rate { get; set; }
    }
}
