//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REAL_Data_Migration_Tool.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblUserTokenPP
    {
        public int Token_Id { get; set; }
        public string Token_User_Id { get; set; }
        public string Token_Code { get; set; }
        public Nullable<byte> Token_Is_Active { get; set; }
        public string Token_Polis { get; set; }
        public Nullable<System.DateTime> Use_Date { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public Nullable<System.DateTime> Modify_Date { get; set; }
    
        public virtual TblUserPP TblUserPP { get; set; }
        public virtual TblUserPPResponse TblUserPPResponse { get; set; }
    }
}
