//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REAL_Data_Migration_Tool.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UpdateNAV
    {
        public System.DateTime Effective_Date { get; set; }
        public string RD { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Subs { get; set; }
        public Nullable<decimal> Reedem { get; set; }
        public Nullable<decimal> Total_Unit { get; set; }
        public Nullable<decimal> Convert { get; set; }
        public Nullable<decimal> Rupiah_Unit { get; set; }
        public Nullable<decimal> Unit_Price { get; set; }
        public string Create_UserId { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public string Modify_UserId { get; set; }
        public Nullable<System.DateTime> Modify_Date { get; set; }
    }
}
