//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMigrationConsoleTools.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPLICATION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public APPLICATION()
        {
            this.APPREL = new HashSet<APPREL>();
            this.BENEFICIARY = new HashSet<BENEFICIARY>();
        }
    
        public string APPLI_NUM { get; set; }
        public string BUSI_CODE { get; set; }
        public long ADDR_ID { get; set; }
        public Nullable<System.DateTime> APPL_DATE { get; set; }
        public Nullable<System.DateTime> APPL_RCV_DATE { get; set; }
        public Nullable<System.DateTime> APPL_ENT_DATE { get; set; }
        public string CURR { get; set; }
        public string STATUS { get; set; }
        public string INS_SEX { get; set; }
        public Nullable<int> INS_AGE { get; set; }
        public string SMOKER { get; set; }
        public string MED_CODE { get; set; }
        public string PAYMETH { get; set; }
        public string DIV_OPT { get; set; }
        public string PAYFREQ { get; set; }
        public Nullable<double> ANN_PREM { get; set; }
        public Nullable<double> NA_PREM { get; set; }
        public Nullable<double> EXT_PREM { get; set; }
        public Nullable<double> MOD_PREM { get; set; }
        public Nullable<long> CADDR_CODE { get; set; }
        public Nullable<int> INS_SAGE { get; set; }
        public Nullable<double> TOT_DISC { get; set; }
        public string ASTRA_DISC { get; set; }
        public string LARGE_DISC { get; set; }
        public string OTHER_DISC { get; set; }
        public Nullable<int> OTHER_DISC_VAL { get; set; }
        public string AGENT_REL { get; set; }
        public string REASON { get; set; }
        public string STCARD { get; set; }
        public string PREM_TYPE { get; set; }
        public Nullable<System.DateTime> DECISION_DATE { get; set; }
        public string CANCEL_FLAG { get; set; }
        public Nullable<System.DateTime> UPD_DATE { get; set; }
        public string CODER { get; set; }
        public string PACKAGE { get; set; }
        public string AGENCODE2 { get; set; }
        public string AGENNAME2 { get; set; }
    
        public virtual ADDRESS ADDRESS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APPREL> APPREL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BENEFICIARY> BENEFICIARY { get; set; }
    }
}
