//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMigrationConsoleTools.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPREL
    {
        public long RL_ID { get; set; }
        public string RELA_CODE { get; set; }
        public Nullable<long> H_ADDR { get; set; }
        public Nullable<long> B_ADDR { get; set; }
        public string APPLI_NUM { get; set; }
        public Nullable<long> CLIENT_ID { get; set; }
        public string STATUS { get; set; }
        public string OCU1 { get; set; }
        public string OCU2 { get; set; }
        public string RELATION { get; set; }
        public string COMPANYNM { get; set; }
        public string PERSONID { get; set; }
        public string PERSONID_TYPE { get; set; }
        public Nullable<int> OCCU_CLASS { get; set; }
    
        public virtual APPLICATION APPLICATION { get; set; }
        public virtual CLIENT CLIENT { get; set; }
    }
}
