//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMigrationConsoleTools.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class BENEFICIARY
    {
        public long BEN_ID { get; set; }
        public string APPLI_NUM { get; set; }
        public string NAME { get; set; }
        public Nullable<double> SHARE { get; set; }
        public string RELATION { get; set; }
    
        public virtual APPLICATION APPLICATION { get; set; }
    }
}
