//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMigrationConsoleTools.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLIENT()
        {
            this.APPREL = new HashSet<APPREL>();
        }
    
        public long CLIENT_ID { get; set; }
        public string MARITAL_ST { get; set; }
        public string TITLE { get; set; }
        public string NAME { get; set; }
        public string SEX { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string POB { get; set; }
        public string NATIONALITY { get; set; }
        public string LOYAL_CARD { get; set; }
        public string H_ADDR { get; set; }
        public string B_ADDR { get; set; }
        public string N_ADDR { get; set; }
        public string KTP { get; set; }
        public string SIM { get; set; }
        public string PASSPORT { get; set; }
        public string MOTHERNAME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APPREL> APPREL { get; set; }
    }
}
