//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMigrationConsoleTools.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class EndorsPolisIIL
    {
        public string endorsement_id { get; set; }
        public Nullable<System.DateTime> endorsement_date { get; set; }
        public string endorsement_remarks { get; set; }
        public string SPAJ { get; set; }
        public string Polis { get; set; }
        public string Nama_TT { get; set; }
        public Nullable<System.DateTime> Tgl_TT { get; set; }
        public string Jkelamin_TT { get; set; }
        public string jID_TT { get; set; }
        public string nID_TT { get; set; }
        public string Ibu_TT { get; set; }
        public string Wn_TT { get; set; }
        public string Occ_TT { get; set; }
        public string WrkPlc_TT { get; set; }
        public string NWrk_TT { get; set; }
        public string Kode_Pos { get; set; }
        public string Alamat1_Tt { get; set; }
        public string Alamat2_Tt { get; set; }
        public string Kel_Tt { get; set; }
        public string Kec_TT { get; set; }
        public string Kota_TT { get; set; }
        public string Prov_TT { get; set; }
        public string Tel_TT { get; set; }
        public string Hp_TT { get; set; }
        public string Email_TT { get; set; }
        public string StatToTT { get; set; }
        public string NPWP_TT { get; set; }
        public string Marital { get; set; }
        public Nullable<int> Usia { get; set; }
        public string Nama_PP { get; set; }
        public Nullable<System.DateTime> Tgl_PP { get; set; }
        public string Jk_PP { get; set; }
        public string jID_PP { get; set; }
        public string nID_PP { get; set; }
        public string Ibu_PP { get; set; }
        public string Wn_PP { get; set; }
        public string Occ_PP { get; set; }
        public string WrkPlc_PP { get; set; }
        public string NWrk_PP { get; set; }
        public string Kode_Pos1 { get; set; }
        public string Alamat1_PP { get; set; }
        public string Alamat2_PP { get; set; }
        public string Kel_PP { get; set; }
        public string Kec_PP { get; set; }
        public string Kota_PP { get; set; }
        public string Prov_PP { get; set; }
        public string Tel_PP { get; set; }
        public string Hp_PP { get; set; }
        public string Email_PP { get; set; }
        public string StaPPoPP { get; set; }
        public string NPWP_PP { get; set; }
        public string Penghasilan { get; set; }
        public string SumberDana { get; set; }
        public string NamaRek { get; set; }
        public string NamaBank { get; set; }
        public string NoRek { get; set; }
        public string CabangRek { get; set; }
        public string BenNama1 { get; set; }
        public string Hub1 { get; set; }
        public Nullable<decimal> Percent1 { get; set; }
        public string BenNama2 { get; set; }
        public string Hub2 { get; set; }
        public Nullable<decimal> Percent2 { get; set; }
        public string BenNama3 { get; set; }
        public string Hub3 { get; set; }
        public Nullable<decimal> Percent3 { get; set; }
        public string BenNama4 { get; set; }
        public string Hub4 { get; set; }
        public Nullable<decimal> Percent4 { get; set; }
        public string MataUang { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<int> MBI { get; set; }
        public Nullable<int> MPI { get; set; }
        public Nullable<decimal> UP { get; set; }
        public Nullable<decimal> Prem_Dsr { get; set; }
        public Nullable<decimal> TopUP { get; set; }
        public Nullable<decimal> TotPrem { get; set; }
        public string JenisInvest { get; set; }
        public string AlokasiInvest { get; set; }
        public string TTD { get; set; }
        public Nullable<System.DateTime> Tgl_Ttd { get; set; }
        public string Smoker { get; set; }
        public string No_Agen { get; set; }
        public string Nama_Agen { get; set; }
        public string Cabang_Agen { get; set; }
        public Nullable<System.DateTime> Submission_Date { get; set; }
        public string User { get; set; }
        public string Marital_PP { get; set; }
        public Nullable<int> Usia_PP { get; set; }
        public Nullable<System.DateTime> Accept_Date { get; set; }
        public Nullable<System.DateTime> Last_Withdrawal { get; set; }
        public Nullable<System.DateTime> Transaction_date { get; set; }
        public Nullable<int> UsiaTo99 { get; set; }
        public Nullable<System.DateTime> Tgl_Ak_As { get; set; }
        public Nullable<System.DateTime> Tgl_Ak_Pem { get; set; }
        public Nullable<decimal> NAV { get; set; }
        public string UpdateBy { get; set; }
        public string Accept_BY { get; set; }
        public string User_POS { get; set; }
        public string Data_Lama { get; set; }
        public Nullable<System.DateTime> Tanggal_Upd_POS { get; set; }
        public string Last_Policy { get; set; }
        public string Notes { get; set; }
        public string Jenis_Perubahan { get; set; }
        public Nullable<System.DateTime> effective_date { get; set; }
        public Nullable<System.DateTime> Tgl_Mature_MPI { get; set; }
    }
}
