//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMigrationConsoleTools.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class fn_fundnav_
    {
        public string fund_code { get; set; }
        public string currency_code { get; set; }
        public System.DateTime effective_date { get; set; }
        public System.DateTime entry_date { get; set; }
        public decimal price { get; set; }
    }
}
