//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMigrationConsoleTools.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPPMature
    {
        public string No_Polis { get; set; }
        public Nullable<int> Mature_day { get; set; }
        public Nullable<int> Mature_month { get; set; }
        public Nullable<int> Mature_year { get; set; }
        public Nullable<System.DateTime> Mature { get; set; }
        public Nullable<System.DateTime> SPAJDate { get; set; }
        public Nullable<System.DateTime> UWDate { get; set; }
        public Nullable<System.DateTime> AcceptDate { get; set; }
    }
}
