//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMigrationConsoleTools.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ISL_APP_CUSTOMERS_TMP
    {
        public int N_CUSTOMER_ID { get; set; }
        public string C_CUSTOMER_NAME { get; set; }
        public string C_CUSTOMER_NAME_OLD { get; set; }
        public string C_MARITAL_TYPE { get; set; }
        public string C_MARITAL_TYPE_OLD { get; set; }
        public string C_SEX { get; set; }
        public string C_SEX_OLD { get; set; }
        public System.DateTime D_DOB { get; set; }
        public Nullable<System.DateTime> D_DOB_OLD { get; set; }
        public string C_PLACE_OF_BIRTH { get; set; }
        public string C_PLACE_OF_BIRTH_OLD { get; set; }
        public string C_ADDRESS_1 { get; set; }
        public string C_ADDRESS_1_OLD { get; set; }
        public string C_ADDRESS_2 { get; set; }
        public string C_ADDRESS_2_OLD { get; set; }
        public string C_ADDRESS_3 { get; set; }
        public string C_ADDRESS_3_OLD { get; set; }
        public string N_POSTAL_CODE { get; set; }
        public string N_POSTAL_CODE_OLD { get; set; }
        public string C_CITY { get; set; }
        public string C_CITY_OLD { get; set; }
        public string C_PROVINCE { get; set; }
        public string C_PROVINCE_OLD { get; set; }
        public string C_COUNTRY { get; set; }
        public string C_COUNTRY_OLD { get; set; }
        public string C_PHONE { get; set; }
        public string C_PHONE_OLD { get; set; }
        public string C_HP { get; set; }
        public string C_HP_OLD { get; set; }
        public string C_FAX { get; set; }
        public string C_FAX_OLD { get; set; }
        public string C_EMAIL_ADDRESS { get; set; }
        public string C_EMAIL_ADDRESS_OLD { get; set; }
        public string C_ID_CARD_NUMBER { get; set; }
        public string C_ID_CARD_NUMBER_OLD { get; set; }
        public string C_OCCUPATION { get; set; }
        public string C_OCCUPATION_OLD { get; set; }
        public string C_COMPANY_NAME { get; set; }
        public string C_COMPANY_NAME_OLD { get; set; }
        public string C_STATUS { get; set; }
        public int N_CREATED_BY { get; set; }
        public System.DateTime D_CREATION_DATE { get; set; }
        public int N_LAST_UPDATED_BY { get; set; }
        public System.DateTime D_LAST_UPDATED_DATE { get; set; }
        public Nullable<int> N_VERIFIED_BY { get; set; }
        public Nullable<System.DateTime> D_VERIFIED_DATE { get; set; }
    }
}
