//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMigrationConsoleTools.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ISL_APP_STG_DTL
    {
        public int N_STAGING_DTL_ID { get; set; }
        public int N_STAGING_HDR_ID { get; set; }
        public string C_NO_SPAJ { get; set; }
        public string C_POLICY_HOLDER_NAME { get; set; }
        public Nullable<int> N_POLICY_HOLDER_CUST_ID { get; set; }
        public string C_MARITAL_STATUS { get; set; }
        public string C_SEX { get; set; }
        public System.DateTime D_DATE_OF_BIRTH { get; set; }
        public string C_PLACE_OF_BIRTH { get; set; }
        public string C_ADDRESS_1 { get; set; }
        public string C_ADDRESS_2 { get; set; }
        public string C_ADDRESS_3 { get; set; }
        public string C_POSTAL_CODE { get; set; }
        public string C_CITY { get; set; }
        public string C_PROVINCE { get; set; }
        public string C_COUNTRY { get; set; }
        public string C_PHONE { get; set; }
        public string C_HP { get; set; }
        public string C_FAX { get; set; }
        public string C_EMAIL { get; set; }
        public string C_ID_CARD_NUMBER { get; set; }
        public string C_OCCUPATION { get; set; }
        public string C_COMPANY_NAME { get; set; }
        public Nullable<int> N_BANK_ID { get; set; }
        public string C_BANK_NAME { get; set; }
        public string C_BANK_BRANCH { get; set; }
        public string C_BANK_ACCOUNT { get; set; }
        public string C_BANK_ACCOUNT_NAME { get; set; }
        public string C_BANK_CITY { get; set; }
        public string C_INSURED_NAME { get; set; }
        public Nullable<int> N_INSURED_CUST_ID { get; set; }
        public string C_INSURED_MARTIAL_STATUS { get; set; }
        public string C_INSURED_SEX { get; set; }
        public System.DateTime C_INSURED_DATE_OF_BIRTH { get; set; }
        public string C_INSURED_PLACE_OF_BIRTH { get; set; }
        public string C_INSURED_ADDRESS_1 { get; set; }
        public string C_INSURED_ADDRESS_2 { get; set; }
        public string C_INSURED_ADDRESS_3 { get; set; }
        public string C_INSURED_POSTAL_CODE { get; set; }
        public string C_INSURED_CITY { get; set; }
        public string C_INSURED_PROVINCE { get; set; }
        public string C_INSURED_COUNTRY { get; set; }
        public string C_INSURED_PHONE { get; set; }
        public string C_INSURED_HP { get; set; }
        public string C_INSURED_FAX { get; set; }
        public string C_INSURED_EMAIL { get; set; }
        public string C_INSURED_ID_CARD_NUMBER { get; set; }
        public string C_INSURED_OCCUPATION { get; set; }
        public string C_INSURED_COMPANY_NAME { get; set; }
        public string C_INSURED_RELATION { get; set; }
        public string C_INSURED_PAYOR_NAME { get; set; }
        public string C_BENEF_NAME_1 { get; set; }
        public string C_BENEF_SEX_1 { get; set; }
        public System.DateTime D_BENEF_DOB_1 { get; set; }
        public double N_BENEF_SHARE_1 { get; set; }
        public string N_BENEF_RELATION_TYPE_1 { get; set; }
        public string C_BENEF_NAME_2 { get; set; }
        public string C_BENEF_SEX_2 { get; set; }
        public Nullable<System.DateTime> D_BENEF_DOB_2 { get; set; }
        public Nullable<double> N_BENEF_SHARE_2 { get; set; }
        public string N_BENEF_RELATION_TYPE_2 { get; set; }
        public string C_BENEF_NAME_3 { get; set; }
        public string C_BENEF_SEX_3 { get; set; }
        public Nullable<System.DateTime> D_BENEF_DOB_3 { get; set; }
        public Nullable<double> N_BENEF_SHARE_3 { get; set; }
        public string N_BENEF_RELATION_TYPE_3 { get; set; }
        public string C_BENEF_NAME_4 { get; set; }
        public string C_BENEF_SEX_4 { get; set; }
        public Nullable<System.DateTime> D_BENEF_DOB_4 { get; set; }
        public Nullable<double> N_BENEF_SHARE_4 { get; set; }
        public string N_BENEF_RELATION_TYPE_4 { get; set; }
        public string C_AGENT_CODE { get; set; }
        public System.DateTime D_ENTRY_DATE { get; set; }
        public string C_PRODUCT_NAME { get; set; }
        public string C_STATUS_MESSAGE { get; set; }
        public int N_CREATED_BY { get; set; }
        public System.DateTime D_CREATION_DATE { get; set; }
        public int N_LAST_UPDATED_BY { get; set; }
        public System.DateTime D_LAST_UPDATED_DATE { get; set; }
    }
}
