//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMigrationConsoleTools.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ISL_APP_PRODUCTS
    {
        public int N_PRODUCT_ID { get; set; }
        public string C_PRODUCT_CODE { get; set; }
        public string C_PRODUCT_NAME { get; set; }
        public int N_FREE_LOOK_DAYS { get; set; }
        public int N_PCF_GRACE_PERIOD_DAYS { get; set; }
        public string C_PCF_GENERATED_EVERY { get; set; }
        public int N_MAX_PCF_TO_GENERATE { get; set; }
        public double N_PREMIUM_AMOUNT { get; set; }
        public int N_INSURANCE_LIFE_IN_YEARS { get; set; }
        public int N_CREATED_BY { get; set; }
        public System.DateTime D_CREATION_DATE { get; set; }
        public int N_LAST_UPDATED_BY { get; set; }
        public System.DateTime D_LAST_UPDATED_DATE { get; set; }
    }
}
