//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMigrationConsoleTools.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ISL_APP_LOGS
    {
        public int N_LOG_ID { get; set; }
        public string C_MODULE_NAME { get; set; }
        public string C_PROCEDURE_NAME { get; set; }
        public string C_LOG_TEXT { get; set; }
        public Nullable<byte> N_ERROR_SEVERTITY { get; set; }
        public Nullable<byte> N_ERROR_STATE { get; set; }
        public int N_CREATED_BY { get; set; }
        public System.DateTime D_CREATION_DATE { get; set; }
        public int N_LAST_UPDATED_BY { get; set; }
        public System.DateTime D_LAST_UPDATED_DATE { get; set; }
    }
}
