//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMigrationConsoleTools.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ISL_OPS_ENDORSE_IS
    {
        public int N_ENDORSEMENT_ID { get; set; }
        public string C_ENDORSEMENT_NO { get; set; }
        public Nullable<System.DateTime> D_ENDORSE_DATE { get; set; }
        public Nullable<System.DateTime> D_CONFIRM_DATE { get; set; }
        public int N_POLICY_ID { get; set; }
        public string C_ID_CARD_NUMBER { get; set; }
        public string C_INSURED_NAME { get; set; }
        public string C_MARITAL_TYPE { get; set; }
        public string C_SEX { get; set; }
        public string C_PLACE_OF_BIRTH { get; set; }
        public Nullable<System.DateTime> D_DOB { get; set; }
        public string C_EMAIL_ADDRESS { get; set; }
        public string C_HP { get; set; }
        public string C_ADDRESS_1 { get; set; }
        public string C_ADDRESS_2 { get; set; }
        public string C_ADDRESS_3 { get; set; }
        public string N_POSTAL_CODE { get; set; }
        public string C_CITY { get; set; }
        public string C_PROVINCE { get; set; }
        public string C_COUNTRY { get; set; }
        public string C_ENDORSEMENT_TYPE { get; set; }
        public string C_STATUS { get; set; }
        public int N_EXISTS { get; set; }
        public string C_NEW_ID_CARD_NUMBER { get; set; }
        public string C_NEW_INSURED_NAME { get; set; }
        public string C_NEW_MARITAL_TYPE { get; set; }
        public string C_NEW_SEX { get; set; }
        public string C_NEW_PLACE_OF_BIRTH { get; set; }
        public Nullable<System.DateTime> D_NEW_DOB { get; set; }
        public string C_NEW_EMAIL_ADDRESS { get; set; }
        public string C_NEW_HP { get; set; }
        public string C_NEW_ADDRESS_1 { get; set; }
        public string C_NEW_ADDRESS_2 { get; set; }
        public string C_NEW_ADDRESS_3 { get; set; }
        public string N_NEW_POSTAL_CODE { get; set; }
        public string C_NEW_CITY { get; set; }
        public string C_NEW_PROVINCE { get; set; }
        public string C_NEW_COUNTRY { get; set; }
        public int N_CREATED_BY { get; set; }
        public System.DateTime D_CREATION_DATE { get; set; }
        public int N_LAST_UPDATED_BY { get; set; }
        public System.DateTime D_LAST_UPDATED_DATE { get; set; }
    }
}
