//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMigrationConsoleTools.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ISL_OPS_POLICY_PCF
    {
        public int N_POLICY_PCF_ID { get; set; }
        public int N_POLICY_ID { get; set; }
        public System.DateTime D_START_DATE { get; set; }
        public System.DateTime D_END_DATE { get; set; }
        public double N_AMOUNT { get; set; }
        public string C_COMMISSION_TYPE { get; set; }
        public Nullable<System.DateTime> D_SETTLEMENT_DATE { get; set; }
        public Nullable<double> N_SETTLED_AMOUNT { get; set; }
        public int N_CREATED_BY { get; set; }
        public System.DateTime D_CREATION_DATE { get; set; }
        public int N_LAST_UPDATED_BY { get; set; }
        public System.DateTime D_LAST_UPDATED_DATE { get; set; }
    }
}
