//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMigrationConsoleTools.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ISL_APP_CUSTOMER_BANKS_TMP
    {
        public int N_CUST_BANK_ID { get; set; }
        public int N_BANK_ID { get; set; }
        public Nullable<int> N_BANK_ID_OLD { get; set; }
        public int N_CUSTOMER_ID { get; set; }
        public string C_BANK_BRANCH { get; set; }
        public string C_BANK_BRANCH_OLD { get; set; }
        public string C_BANK_ACCOUNT_NO { get; set; }
        public string C_BANK_ACCOUNT_NO_OLD { get; set; }
        public string C_BANK_ACCOUNT_NAME { get; set; }
        public string C_BANK_ACCOUNT_NAME_OLD { get; set; }
        public string C_BANK_CITY { get; set; }
        public string C_BANK_CITY_OLD { get; set; }
        public string C_STATUS { get; set; }
        public int N_CREATED_BY { get; set; }
        public System.DateTime D_CREATION_DATE { get; set; }
        public int N_LAST_UPDATED_BY { get; set; }
        public System.DateTime D_LAST_UPDATED_DATE { get; set; }
        public Nullable<int> N_VERIFIED_BY { get; set; }
        public Nullable<System.DateTime> D_VERIFIED_DATE { get; set; }
    }
}
