//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMigrationConsoleTools.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ISL_FIN_UPD_HDR
    {
        public int N_UPLOAD_HDR_ID { get; set; }
        public string C_FILENAME { get; set; }
        public Nullable<int> N_TOTAL_DATA { get; set; }
        public Nullable<double> N_AMOUNT { get; set; }
        public string C_STATUS { get; set; }
        public System.DateTime D_RECON_DATE { get; set; }
        public int N_CREATED_BY { get; set; }
        public System.DateTime D_CREATION_DATE { get; set; }
        public int N_LAST_UPDATED_BY { get; set; }
        public System.DateTime D_LAST_UPDATED_DATE { get; set; }
    }
}
