//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMigrationConsoleTools.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ISL_APP_LOGIN_ATTEMPT
    {
        public string C_CODE { get; set; }
        public int N_USER_ID { get; set; }
        public System.DateTime D_CREATED_DATE { get; set; }
    }
}
