//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMigrationConsoleTools.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ISL_OPS_CLAIMS
    {
        public int N_CLAIM_ID { get; set; }
        public string C_CLAIM_NO { get; set; }
        public int N_POLICY_ID { get; set; }
        public string C_CLAIM_TYPE { get; set; }
        public int N_BANK_ID { get; set; }
        public string C_BANK_BRANCH { get; set; }
        public string C_BANK_ACCOUNT_NAME { get; set; }
        public string C_BANK_ACCOUNT_NO { get; set; }
        public Nullable<double> N_AMOUNT { get; set; }
        public string C_SOURCE_DATA { get; set; }
        public System.DateTime D_CLAIM_REQUEST_DATE { get; set; }
        public Nullable<System.DateTime> D_INCIDENT_DATE { get; set; }
        public string C_INCIDENT_PLACE { get; set; }
        public string C_DIAGNOSE { get; set; }
        public string C_NOTES { get; set; }
        public Nullable<System.DateTime> D_PAID_DATE { get; set; }
        public string C_PAID_SLIP_IMG_PATH { get; set; }
        public string C_STATUS { get; set; }
        public int N_CREATED_BY { get; set; }
        public System.DateTime D_CREATION_DATE { get; set; }
        public int N_LAST_UPDATED_BY { get; set; }
        public System.DateTime D_LAST_UPDATED_DATE { get; set; }
    }
}
