//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMigrationConsoleTools.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ISL_OPS_ENDORSE_BN
    {
        public int N_ENDORSEMENT_ID { get; set; }
        public string C_ENDORSEMENT_NO { get; set; }
        public Nullable<System.DateTime> D_ENDORSE_DATE { get; set; }
        public Nullable<System.DateTime> D_CONFIRM_DATE { get; set; }
        public int N_POLICY_ID { get; set; }
        public string C_HOLDER_NAME { get; set; }
        public string C_BENEF_NAME_1 { get; set; }
        public string C_BENEF_SEX_1 { get; set; }
        public Nullable<System.DateTime> D_BENEF_DOB_1 { get; set; }
        public Nullable<double> N_BENEF_SHARE_1 { get; set; }
        public string C_BENEF_RELATION_TYPE_1 { get; set; }
        public string C_BENEF_NAME_2 { get; set; }
        public string C_BENEF_SEX_2 { get; set; }
        public Nullable<System.DateTime> D_BENEF_DOB_2 { get; set; }
        public Nullable<double> N_BENEF_SHARE_2 { get; set; }
        public string C_BENEF_RELATION_TYPE_2 { get; set; }
        public string C_BENEF_NAME_3 { get; set; }
        public string C_BENEF_SEX_3 { get; set; }
        public Nullable<System.DateTime> D_BENEF_DOB_3 { get; set; }
        public Nullable<double> N_BENEF_SHARE_3 { get; set; }
        public string C_BENEF_RELATION_TYPE_3 { get; set; }
        public string C_BENEF_NAME_4 { get; set; }
        public string C_BENEF_SEX_4 { get; set; }
        public Nullable<System.DateTime> D_BENEF_DOB_4 { get; set; }
        public Nullable<double> N_BENEF_SHARE_4 { get; set; }
        public string C_BENEF_RELATION_TYPE_4 { get; set; }
        public string C_ENDORSEMENT_TYPE { get; set; }
        public string C_STATUS { get; set; }
        public string C_NEW_BENEF_NAME_1 { get; set; }
        public string C_NEW_BENEF_SEX_1 { get; set; }
        public Nullable<System.DateTime> D_NEW_BENEF_DOB_1 { get; set; }
        public Nullable<double> N_NEW_BENEF_SHARE_1 { get; set; }
        public string C_NEW_BENEF_RELATION_TYPE_1 { get; set; }
        public string C_NEW_BENEF_NAME_2 { get; set; }
        public string C_NEW_BENEF_SEX_2 { get; set; }
        public Nullable<System.DateTime> D_NEW_BENEF_DOB_2 { get; set; }
        public Nullable<double> N_NEW_BENEF_SHARE_2 { get; set; }
        public string C_NEW_BENEF_RELATION_TYPE_2 { get; set; }
        public string C_NEW_BENEF_NAME_3 { get; set; }
        public string C_NEW_BENEF_SEX_3 { get; set; }
        public Nullable<System.DateTime> D_NEW_BENEF_DOB_3 { get; set; }
        public Nullable<double> N_NEW_BENEF_SHARE_3 { get; set; }
        public string C_NEW_BENEF_RELATION_TYPE_3 { get; set; }
        public string C_NEW_BENEF_NAME_4 { get; set; }
        public string C_NEW_BENEF_SEX_4 { get; set; }
        public Nullable<System.DateTime> D_NEW_BENEF_DOB_4 { get; set; }
        public Nullable<double> N_NEW_BENEF_SHARE_4 { get; set; }
        public string C_NEW_BENEF_RELATION_TYPE_4 { get; set; }
        public int N_CREATED_BY { get; set; }
        public System.DateTime D_CREATION_DATE { get; set; }
        public int N_LAST_UPDATED_BY { get; set; }
        public System.DateTime D_LAST_UPDATED_DATE { get; set; }
    }
}
