//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMigrationConsoleTools.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ISL_OPS_POLICIES
    {
        public int N_POLICY_ID { get; set; }
        public int N_PRODUCT_ID { get; set; }
        public string C_NO_SPAJ { get; set; }
        public string C_POLICY_NO { get; set; }
        public string C_AGENT_CODE { get; set; }
        public int N_HOLDER_CUSTOMER_ID { get; set; }
        public int N_INSURED_CUSTOMER_ID { get; set; }
        public string C_HOLDER_INSURED_RELATION_TYPE { get; set; }
        public System.DateTime D_START_DATE { get; set; }
        public System.DateTime D_MATURE_DATE { get; set; }
        public System.DateTime D_FREE_LOOK_LAST_DAY { get; set; }
        public int N_CUST_BANK_ID { get; set; }
        public string C_BENEF_NAME_1 { get; set; }
        public string C_BENEF_SEX_1 { get; set; }
        public System.DateTime D_BENEF_DOB_1 { get; set; }
        public double N_BENEF_SHARE_1 { get; set; }
        public string C_BENEF_RELATION_TYPE_1 { get; set; }
        public string C_BENEF_NAME_2 { get; set; }
        public string C_BENEF_SEX_2 { get; set; }
        public Nullable<System.DateTime> D_BENEF_DOB_2 { get; set; }
        public Nullable<double> N_BENEF_SHARE_2 { get; set; }
        public string C_BENEF_RELATION_TYPE_2 { get; set; }
        public string C_BENEF_NAME_3 { get; set; }
        public string C_BENEF_SEX_3 { get; set; }
        public Nullable<System.DateTime> D_BENEF_DOB_3 { get; set; }
        public Nullable<double> N_BENEF_SHARE_3 { get; set; }
        public string C_BENEF_RELATION_TYPE_3 { get; set; }
        public string C_BENEF_NAME_4 { get; set; }
        public string C_BENEF_SEX_4 { get; set; }
        public Nullable<System.DateTime> D_BENEF_DOB_4 { get; set; }
        public Nullable<double> N_BENEF_SHARE_4 { get; set; }
        public string C_BENEF_RELATION_TYPE_4 { get; set; }
        public string C_STATUS { get; set; }
        public string C_EPOLIS_FILE_PATH { get; set; }
        public Nullable<int> N_STAGING_DTL_ID { get; set; }
        public int N_CREATED_BY { get; set; }
        public System.DateTime D_CREATION_DATE { get; set; }
        public int N_LAST_UPDATED_BY { get; set; }
        public System.DateTime D_LAST_UPDATED_DATE { get; set; }
    }
}
