//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMigrationConsoleTools.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ISL_OPS_ENDORSE_DTL
    {
        public string C_ENDORSEMENT_NO { get; set; }
        public int N_POLICY_ID { get; set; }
        public string C_AS { get; set; }
        public string C_POLICY_NO { get; set; }
        public Nullable<int> N_EXISTS { get; set; }
        public Nullable<int> N_OLD_CUSTOMER_ID { get; set; }
        public Nullable<int> N_NEW_CUSTOMER_ID { get; set; }
        public int N_CREATED_BY { get; set; }
        public System.DateTime D_CREATION_DATE { get; set; }
        public int N_LAST_UPDATED_BY { get; set; }
        public System.DateTime D_LAST_UPDATED_DATE { get; set; }
    }
}
