//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMigrationConsoleTools.DataModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MIGULDBDevEntities : DbContext
    {
        public MIGULDBDevEntities()
            : base("name=MIGULDBDevEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cd_client_> cd_client_ { get; set; }
        public virtual DbSet<fn_fundnav_> fn_fundnav_ { get; set; }
        public virtual DbSet<OldClientIdToNewClientId> OldClientIdToNewClientId { get; set; }
        public virtual DbSet<ps_fund_transaction_history_> ps_fund_transaction_history_ { get; set; }
    
        public virtual ObjectResult<Nullable<int>> spMigrateFnFundnav()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("spMigrateFnFundnav");
        }
    
        public virtual ObjectResult<Nullable<int>> spMigrateFundTransactionFromIlias()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("spMigrateFundTransactionFromIlias");
        }
    
        public virtual ObjectResult<Nullable<int>> spMigrateFuntTransactionMultiUser()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("spMigrateFuntTransactionMultiUser");
        }
    
        public virtual ObjectResult<usp_GetErrorInfo_Result> usp_GetErrorInfo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetErrorInfo_Result>("usp_GetErrorInfo");
        }
    }
}
