//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMigrationConsoleTools.DataModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ISL_PORTALEntities : DbContext
    {
        public ISL_PORTALEntities()
            : base("name=ISL_PORTALEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ISL_APP_CUSTOMER_BANKS> ISL_APP_CUSTOMER_BANKS { get; set; }
        public virtual DbSet<ISL_APP_CUSTOMER_HIST> ISL_APP_CUSTOMER_HIST { get; set; }
        public virtual DbSet<ISL_APP_CUSTOMER_RELATIONSHIPS> ISL_APP_CUSTOMER_RELATIONSHIPS { get; set; }
        public virtual DbSet<ISL_APP_CUSTOMERS> ISL_APP_CUSTOMERS { get; set; }
        public virtual DbSet<ISL_APP_LOGS> ISL_APP_LOGS { get; set; }
        public virtual DbSet<ISL_APP_PRODUCT_BENEFITS> ISL_APP_PRODUCT_BENEFITS { get; set; }
        public virtual DbSet<ISL_APP_PRODUCTS> ISL_APP_PRODUCTS { get; set; }
        public virtual DbSet<ISL_MKT_AGENT_MST> ISL_MKT_AGENT_MST { get; set; }
        public virtual DbSet<ISL_MKT_COMMISSION_ACTION_HIST> ISL_MKT_COMMISSION_ACTION_HIST { get; set; }
        public virtual DbSet<ISL_MKT_COMMISSION_DTL> ISL_MKT_COMMISSION_DTL { get; set; }
        public virtual DbSet<ISL_MKT_COMMISSION_HDR> ISL_MKT_COMMISSION_HDR { get; set; }
        public virtual DbSet<ISL_OPS_CLAIM_ACTION_HIST> ISL_OPS_CLAIM_ACTION_HIST { get; set; }
        public virtual DbSet<ISL_OPS_CLAIM_DOCS> ISL_OPS_CLAIM_DOCS { get; set; }
        public virtual DbSet<ISL_OPS_CLAIMS> ISL_OPS_CLAIMS { get; set; }
        public virtual DbSet<ISL_OPS_ENDORSE_BN> ISL_OPS_ENDORSE_BN { get; set; }
        public virtual DbSet<ISL_OPS_ENDORSE_DTL> ISL_OPS_ENDORSE_DTL { get; set; }
        public virtual DbSet<ISL_OPS_ENDORSE_FILE> ISL_OPS_ENDORSE_FILE { get; set; }
        public virtual DbSet<ISL_OPS_ENDORSE_IS> ISL_OPS_ENDORSE_IS { get; set; }
        public virtual DbSet<ISL_OPS_ENDORSE_PH> ISL_OPS_ENDORSE_PH { get; set; }
        public virtual DbSet<ISL_OPS_POLICIES> ISL_OPS_POLICIES { get; set; }
        public virtual DbSet<ISL_OPS_POLICY_HIST> ISL_OPS_POLICY_HIST { get; set; }
        public virtual DbSet<ISL_OPS_POLICY_PCF> ISL_OPS_POLICY_PCF { get; set; }
        public virtual DbSet<ISL_APP_BANKS> ISL_APP_BANKS { get; set; }
        public virtual DbSet<ISL_APP_CUSTOMER_BANKS_TMP> ISL_APP_CUSTOMER_BANKS_TMP { get; set; }
        public virtual DbSet<ISL_APP_CUSTOMER_RELATIONSHIPS_TMP> ISL_APP_CUSTOMER_RELATIONSHIPS_TMP { get; set; }
        public virtual DbSet<ISL_APP_CUSTOMERS_TMP> ISL_APP_CUSTOMERS_TMP { get; set; }
        public virtual DbSet<ISL_APP_LOGIN_ATTEMPT> ISL_APP_LOGIN_ATTEMPT { get; set; }
        public virtual DbSet<ISL_APP_STG_DTL> ISL_APP_STG_DTL { get; set; }
        public virtual DbSet<ISL_APP_STG_HDR> ISL_APP_STG_HDR { get; set; }
        public virtual DbSet<ISL_APP_STG_HST> ISL_APP_STG_HST { get; set; }
        public virtual DbSet<ISL_FIN_UPD_DTL> ISL_FIN_UPD_DTL { get; set; }
        public virtual DbSet<ISL_FIN_UPD_HDR> ISL_FIN_UPD_HDR { get; set; }
        public virtual DbSet<ISL_OPS_POLICY_TMP> ISL_OPS_POLICY_TMP { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<vw_jiwa> vw_jiwa { get; set; }
        public virtual DbSet<vw_jiwa_db> vw_jiwa_db { get; set; }
    
        public virtual int SP_CALCULATE_COMMISSION(ObjectParameter c_STATUS, ObjectParameter c_STATUS_MESSAGE)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CALCULATE_COMMISSION", c_STATUS, c_STATUS_MESSAGE);
        }
    
        public virtual ObjectResult<SP_COMMISSION_SUMMARY_Result> SP_COMMISSION_SUMMARY()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_COMMISSION_SUMMARY_Result>("SP_COMMISSION_SUMMARY");
        }
    
        public virtual int SP_CREATE_CUSTOMER_BANK(Nullable<int> n_POLICY_HOLDER_CUST_ID, string c_BANK_BRANCH, string c_BANK_ACCOUNT, string c_BANK_ACCOUNT_NAME, string c_BANK_CITY, Nullable<int> n_BANK_ID, Nullable<int> n_USER_ID, ObjectParameter n_CUST_BANK_ID, ObjectParameter c_MSG_OUT)
        {
            var n_POLICY_HOLDER_CUST_IDParameter = n_POLICY_HOLDER_CUST_ID.HasValue ?
                new ObjectParameter("N_POLICY_HOLDER_CUST_ID", n_POLICY_HOLDER_CUST_ID) :
                new ObjectParameter("N_POLICY_HOLDER_CUST_ID", typeof(int));
    
            var c_BANK_BRANCHParameter = c_BANK_BRANCH != null ?
                new ObjectParameter("C_BANK_BRANCH", c_BANK_BRANCH) :
                new ObjectParameter("C_BANK_BRANCH", typeof(string));
    
            var c_BANK_ACCOUNTParameter = c_BANK_ACCOUNT != null ?
                new ObjectParameter("C_BANK_ACCOUNT", c_BANK_ACCOUNT) :
                new ObjectParameter("C_BANK_ACCOUNT", typeof(string));
    
            var c_BANK_ACCOUNT_NAMEParameter = c_BANK_ACCOUNT_NAME != null ?
                new ObjectParameter("C_BANK_ACCOUNT_NAME", c_BANK_ACCOUNT_NAME) :
                new ObjectParameter("C_BANK_ACCOUNT_NAME", typeof(string));
    
            var c_BANK_CITYParameter = c_BANK_CITY != null ?
                new ObjectParameter("C_BANK_CITY", c_BANK_CITY) :
                new ObjectParameter("C_BANK_CITY", typeof(string));
    
            var n_BANK_IDParameter = n_BANK_ID.HasValue ?
                new ObjectParameter("N_BANK_ID", n_BANK_ID) :
                new ObjectParameter("N_BANK_ID", typeof(int));
    
            var n_USER_IDParameter = n_USER_ID.HasValue ?
                new ObjectParameter("N_USER_ID", n_USER_ID) :
                new ObjectParameter("N_USER_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CREATE_CUSTOMER_BANK", n_POLICY_HOLDER_CUST_IDParameter, c_BANK_BRANCHParameter, c_BANK_ACCOUNTParameter, c_BANK_ACCOUNT_NAMEParameter, c_BANK_CITYParameter, n_BANK_IDParameter, n_USER_IDParameter, n_CUST_BANK_ID, c_MSG_OUT);
        }
    
        public virtual int SP_CREATE_CUSTOMER_DATA(string c_CUSTOMER_NAME, string c_MARITAL_TYPE, string c_SEX, Nullable<System.DateTime> d_DOB, string c_PLACE_OF_BIRTH, string c_ADDRESS_1, string c_ADDRESS_2, string c_ADDRESS_3, string n_POSTAL_CODE, string c_CITY, string c_PROVINCE, string c_COUNTRY, string c_PHONE, string c_HP, string c_FAX, string c_EMAIL_ADDRESS, string c_ID_CARD_NUMBER, string c_OCCUPATION, string c_COMPANY_NAME, Nullable<int> n_USER_ID, ObjectParameter n_CUSTOMER_ID, ObjectParameter c_ERROR_MESSAGE)
        {
            var c_CUSTOMER_NAMEParameter = c_CUSTOMER_NAME != null ?
                new ObjectParameter("C_CUSTOMER_NAME", c_CUSTOMER_NAME) :
                new ObjectParameter("C_CUSTOMER_NAME", typeof(string));
    
            var c_MARITAL_TYPEParameter = c_MARITAL_TYPE != null ?
                new ObjectParameter("C_MARITAL_TYPE", c_MARITAL_TYPE) :
                new ObjectParameter("C_MARITAL_TYPE", typeof(string));
    
            var c_SEXParameter = c_SEX != null ?
                new ObjectParameter("C_SEX", c_SEX) :
                new ObjectParameter("C_SEX", typeof(string));
    
            var d_DOBParameter = d_DOB.HasValue ?
                new ObjectParameter("D_DOB", d_DOB) :
                new ObjectParameter("D_DOB", typeof(System.DateTime));
    
            var c_PLACE_OF_BIRTHParameter = c_PLACE_OF_BIRTH != null ?
                new ObjectParameter("C_PLACE_OF_BIRTH", c_PLACE_OF_BIRTH) :
                new ObjectParameter("C_PLACE_OF_BIRTH", typeof(string));
    
            var c_ADDRESS_1Parameter = c_ADDRESS_1 != null ?
                new ObjectParameter("C_ADDRESS_1", c_ADDRESS_1) :
                new ObjectParameter("C_ADDRESS_1", typeof(string));
    
            var c_ADDRESS_2Parameter = c_ADDRESS_2 != null ?
                new ObjectParameter("C_ADDRESS_2", c_ADDRESS_2) :
                new ObjectParameter("C_ADDRESS_2", typeof(string));
    
            var c_ADDRESS_3Parameter = c_ADDRESS_3 != null ?
                new ObjectParameter("C_ADDRESS_3", c_ADDRESS_3) :
                new ObjectParameter("C_ADDRESS_3", typeof(string));
    
            var n_POSTAL_CODEParameter = n_POSTAL_CODE != null ?
                new ObjectParameter("N_POSTAL_CODE", n_POSTAL_CODE) :
                new ObjectParameter("N_POSTAL_CODE", typeof(string));
    
            var c_CITYParameter = c_CITY != null ?
                new ObjectParameter("C_CITY", c_CITY) :
                new ObjectParameter("C_CITY", typeof(string));
    
            var c_PROVINCEParameter = c_PROVINCE != null ?
                new ObjectParameter("C_PROVINCE", c_PROVINCE) :
                new ObjectParameter("C_PROVINCE", typeof(string));
    
            var c_COUNTRYParameter = c_COUNTRY != null ?
                new ObjectParameter("C_COUNTRY", c_COUNTRY) :
                new ObjectParameter("C_COUNTRY", typeof(string));
    
            var c_PHONEParameter = c_PHONE != null ?
                new ObjectParameter("C_PHONE", c_PHONE) :
                new ObjectParameter("C_PHONE", typeof(string));
    
            var c_HPParameter = c_HP != null ?
                new ObjectParameter("C_HP", c_HP) :
                new ObjectParameter("C_HP", typeof(string));
    
            var c_FAXParameter = c_FAX != null ?
                new ObjectParameter("C_FAX", c_FAX) :
                new ObjectParameter("C_FAX", typeof(string));
    
            var c_EMAIL_ADDRESSParameter = c_EMAIL_ADDRESS != null ?
                new ObjectParameter("C_EMAIL_ADDRESS", c_EMAIL_ADDRESS) :
                new ObjectParameter("C_EMAIL_ADDRESS", typeof(string));
    
            var c_ID_CARD_NUMBERParameter = c_ID_CARD_NUMBER != null ?
                new ObjectParameter("C_ID_CARD_NUMBER", c_ID_CARD_NUMBER) :
                new ObjectParameter("C_ID_CARD_NUMBER", typeof(string));
    
            var c_OCCUPATIONParameter = c_OCCUPATION != null ?
                new ObjectParameter("C_OCCUPATION", c_OCCUPATION) :
                new ObjectParameter("C_OCCUPATION", typeof(string));
    
            var c_COMPANY_NAMEParameter = c_COMPANY_NAME != null ?
                new ObjectParameter("C_COMPANY_NAME", c_COMPANY_NAME) :
                new ObjectParameter("C_COMPANY_NAME", typeof(string));
    
            var n_USER_IDParameter = n_USER_ID.HasValue ?
                new ObjectParameter("N_USER_ID", n_USER_ID) :
                new ObjectParameter("N_USER_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CREATE_CUSTOMER_DATA", c_CUSTOMER_NAMEParameter, c_MARITAL_TYPEParameter, c_SEXParameter, d_DOBParameter, c_PLACE_OF_BIRTHParameter, c_ADDRESS_1Parameter, c_ADDRESS_2Parameter, c_ADDRESS_3Parameter, n_POSTAL_CODEParameter, c_CITYParameter, c_PROVINCEParameter, c_COUNTRYParameter, c_PHONEParameter, c_HPParameter, c_FAXParameter, c_EMAIL_ADDRESSParameter, c_ID_CARD_NUMBERParameter, c_OCCUPATIONParameter, c_COMPANY_NAMEParameter, n_USER_IDParameter, n_CUSTOMER_ID, c_ERROR_MESSAGE);
        }
    
        public virtual int SP_CREATE_CUSTOMER_RELATION(Nullable<int> pOLICY_HOLDER_CUST_ID, Nullable<int> iNSURED_CUST_ID, string c_RELATION_TYPE, Nullable<int> n_USER_ID, ObjectParameter n_CUST_REL_ID, ObjectParameter c_ERROR_MSG)
        {
            var pOLICY_HOLDER_CUST_IDParameter = pOLICY_HOLDER_CUST_ID.HasValue ?
                new ObjectParameter("POLICY_HOLDER_CUST_ID", pOLICY_HOLDER_CUST_ID) :
                new ObjectParameter("POLICY_HOLDER_CUST_ID", typeof(int));
    
            var iNSURED_CUST_IDParameter = iNSURED_CUST_ID.HasValue ?
                new ObjectParameter("INSURED_CUST_ID", iNSURED_CUST_ID) :
                new ObjectParameter("INSURED_CUST_ID", typeof(int));
    
            var c_RELATION_TYPEParameter = c_RELATION_TYPE != null ?
                new ObjectParameter("C_RELATION_TYPE", c_RELATION_TYPE) :
                new ObjectParameter("C_RELATION_TYPE", typeof(string));
    
            var n_USER_IDParameter = n_USER_ID.HasValue ?
                new ObjectParameter("N_USER_ID", n_USER_ID) :
                new ObjectParameter("N_USER_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CREATE_CUSTOMER_RELATION", pOLICY_HOLDER_CUST_IDParameter, iNSURED_CUST_IDParameter, c_RELATION_TYPEParameter, n_USER_IDParameter, n_CUST_REL_ID, c_ERROR_MSG);
        }
    
        public virtual int SP_CREATE_LOG(string c_MODULE_NAME, string c_PROCEDURE_NAME, string c_LOG_TEXT, Nullable<byte> n_ERROR_SEVERTITY, Nullable<byte> n_ERROR_STATE, Nullable<int> n_USER_ID)
        {
            var c_MODULE_NAMEParameter = c_MODULE_NAME != null ?
                new ObjectParameter("C_MODULE_NAME", c_MODULE_NAME) :
                new ObjectParameter("C_MODULE_NAME", typeof(string));
    
            var c_PROCEDURE_NAMEParameter = c_PROCEDURE_NAME != null ?
                new ObjectParameter("C_PROCEDURE_NAME", c_PROCEDURE_NAME) :
                new ObjectParameter("C_PROCEDURE_NAME", typeof(string));
    
            var c_LOG_TEXTParameter = c_LOG_TEXT != null ?
                new ObjectParameter("C_LOG_TEXT", c_LOG_TEXT) :
                new ObjectParameter("C_LOG_TEXT", typeof(string));
    
            var n_ERROR_SEVERTITYParameter = n_ERROR_SEVERTITY.HasValue ?
                new ObjectParameter("N_ERROR_SEVERTITY", n_ERROR_SEVERTITY) :
                new ObjectParameter("N_ERROR_SEVERTITY", typeof(byte));
    
            var n_ERROR_STATEParameter = n_ERROR_STATE.HasValue ?
                new ObjectParameter("N_ERROR_STATE", n_ERROR_STATE) :
                new ObjectParameter("N_ERROR_STATE", typeof(byte));
    
            var n_USER_IDParameter = n_USER_ID.HasValue ?
                new ObjectParameter("N_USER_ID", n_USER_ID) :
                new ObjectParameter("N_USER_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CREATE_LOG", c_MODULE_NAMEParameter, c_PROCEDURE_NAMEParameter, c_LOG_TEXTParameter, n_ERROR_SEVERTITYParameter, n_ERROR_STATEParameter, n_USER_IDParameter);
        }
    
        public virtual int SP_CREATE_PCF(Nullable<int> n_POLICY_ID, Nullable<System.DateTime> d_START_DATE, Nullable<int> n_GRACE_PERIOD, Nullable<double> n_AMOUNT, Nullable<int> mAX_PCF_TO_GENERATE, Nullable<int> n_USER_ID, ObjectParameter retVal, ObjectParameter outErrMsg)
        {
            var n_POLICY_IDParameter = n_POLICY_ID.HasValue ?
                new ObjectParameter("N_POLICY_ID", n_POLICY_ID) :
                new ObjectParameter("N_POLICY_ID", typeof(int));
    
            var d_START_DATEParameter = d_START_DATE.HasValue ?
                new ObjectParameter("D_START_DATE", d_START_DATE) :
                new ObjectParameter("D_START_DATE", typeof(System.DateTime));
    
            var n_GRACE_PERIODParameter = n_GRACE_PERIOD.HasValue ?
                new ObjectParameter("N_GRACE_PERIOD", n_GRACE_PERIOD) :
                new ObjectParameter("N_GRACE_PERIOD", typeof(int));
    
            var n_AMOUNTParameter = n_AMOUNT.HasValue ?
                new ObjectParameter("N_AMOUNT", n_AMOUNT) :
                new ObjectParameter("N_AMOUNT", typeof(double));
    
            var mAX_PCF_TO_GENERATEParameter = mAX_PCF_TO_GENERATE.HasValue ?
                new ObjectParameter("MAX_PCF_TO_GENERATE", mAX_PCF_TO_GENERATE) :
                new ObjectParameter("MAX_PCF_TO_GENERATE", typeof(int));
    
            var n_USER_IDParameter = n_USER_ID.HasValue ?
                new ObjectParameter("N_USER_ID", n_USER_ID) :
                new ObjectParameter("N_USER_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CREATE_PCF", n_POLICY_IDParameter, d_START_DATEParameter, n_GRACE_PERIODParameter, n_AMOUNTParameter, mAX_PCF_TO_GENERATEParameter, n_USER_IDParameter, retVal, outErrMsg);
        }
    
        public virtual int SP_CREATE_POLICY(Nullable<int> n_PRODUCT_ID, string c_NO_SPAJ, string c_AGENT_CODE, Nullable<int> n_HOLDER_CUSTOMER_ID, Nullable<int> n_INSURED_CUSTOMER_ID, string c_HOLDER_INSURED_RELATION_TYPE, Nullable<System.DateTime> d_START_DATE, Nullable<System.DateTime> d_MATURE_DATE, Nullable<System.DateTime> d_FREE_LOOK_LAST_DAY, Nullable<int> n_CUST_BANK_ID, string c_BENEF_NAME_1, string c_BENEF_SEX_1, Nullable<System.DateTime> d_BENEF_DOB_1, Nullable<double> n_BENEF_SHARE_1, string c_BENEF_RELATION_TYPE_1, string c_BENEF_NAME_2, string c_BENEF_SEX_2, Nullable<System.DateTime> d_BENEF_DOB_2, Nullable<double> n_BENEF_SHARE_2, string c_BENEF_RELATION_TYPE_2, string c_BENEF_NAME_3, string c_BENEF_SEX_3, Nullable<System.DateTime> d_BENEF_DOB_3, Nullable<double> n_BENEF_SHARE_3, string c_BENEF_RELATION_TYPE_3, string c_BENEF_NAME_4, string c_BENEF_SEX_4, Nullable<System.DateTime> d_BENEF_DOB_4, Nullable<double> n_BENEF_SHARE_4, string c_BENEF_RELATION_TYPE_4, Nullable<int> n_STAGING_DTL_ID, Nullable<int> n_USER_ID, ObjectParameter n_POLICY_ID, ObjectParameter outErrMsg)
        {
            var n_PRODUCT_IDParameter = n_PRODUCT_ID.HasValue ?
                new ObjectParameter("N_PRODUCT_ID", n_PRODUCT_ID) :
                new ObjectParameter("N_PRODUCT_ID", typeof(int));
    
            var c_NO_SPAJParameter = c_NO_SPAJ != null ?
                new ObjectParameter("C_NO_SPAJ", c_NO_SPAJ) :
                new ObjectParameter("C_NO_SPAJ", typeof(string));
    
            var c_AGENT_CODEParameter = c_AGENT_CODE != null ?
                new ObjectParameter("C_AGENT_CODE", c_AGENT_CODE) :
                new ObjectParameter("C_AGENT_CODE", typeof(string));
    
            var n_HOLDER_CUSTOMER_IDParameter = n_HOLDER_CUSTOMER_ID.HasValue ?
                new ObjectParameter("N_HOLDER_CUSTOMER_ID", n_HOLDER_CUSTOMER_ID) :
                new ObjectParameter("N_HOLDER_CUSTOMER_ID", typeof(int));
    
            var n_INSURED_CUSTOMER_IDParameter = n_INSURED_CUSTOMER_ID.HasValue ?
                new ObjectParameter("N_INSURED_CUSTOMER_ID", n_INSURED_CUSTOMER_ID) :
                new ObjectParameter("N_INSURED_CUSTOMER_ID", typeof(int));
    
            var c_HOLDER_INSURED_RELATION_TYPEParameter = c_HOLDER_INSURED_RELATION_TYPE != null ?
                new ObjectParameter("C_HOLDER_INSURED_RELATION_TYPE", c_HOLDER_INSURED_RELATION_TYPE) :
                new ObjectParameter("C_HOLDER_INSURED_RELATION_TYPE", typeof(string));
    
            var d_START_DATEParameter = d_START_DATE.HasValue ?
                new ObjectParameter("D_START_DATE", d_START_DATE) :
                new ObjectParameter("D_START_DATE", typeof(System.DateTime));
    
            var d_MATURE_DATEParameter = d_MATURE_DATE.HasValue ?
                new ObjectParameter("D_MATURE_DATE", d_MATURE_DATE) :
                new ObjectParameter("D_MATURE_DATE", typeof(System.DateTime));
    
            var d_FREE_LOOK_LAST_DAYParameter = d_FREE_LOOK_LAST_DAY.HasValue ?
                new ObjectParameter("D_FREE_LOOK_LAST_DAY", d_FREE_LOOK_LAST_DAY) :
                new ObjectParameter("D_FREE_LOOK_LAST_DAY", typeof(System.DateTime));
    
            var n_CUST_BANK_IDParameter = n_CUST_BANK_ID.HasValue ?
                new ObjectParameter("N_CUST_BANK_ID", n_CUST_BANK_ID) :
                new ObjectParameter("N_CUST_BANK_ID", typeof(int));
    
            var c_BENEF_NAME_1Parameter = c_BENEF_NAME_1 != null ?
                new ObjectParameter("C_BENEF_NAME_1", c_BENEF_NAME_1) :
                new ObjectParameter("C_BENEF_NAME_1", typeof(string));
    
            var c_BENEF_SEX_1Parameter = c_BENEF_SEX_1 != null ?
                new ObjectParameter("C_BENEF_SEX_1", c_BENEF_SEX_1) :
                new ObjectParameter("C_BENEF_SEX_1", typeof(string));
    
            var d_BENEF_DOB_1Parameter = d_BENEF_DOB_1.HasValue ?
                new ObjectParameter("D_BENEF_DOB_1", d_BENEF_DOB_1) :
                new ObjectParameter("D_BENEF_DOB_1", typeof(System.DateTime));
    
            var n_BENEF_SHARE_1Parameter = n_BENEF_SHARE_1.HasValue ?
                new ObjectParameter("N_BENEF_SHARE_1", n_BENEF_SHARE_1) :
                new ObjectParameter("N_BENEF_SHARE_1", typeof(double));
    
            var c_BENEF_RELATION_TYPE_1Parameter = c_BENEF_RELATION_TYPE_1 != null ?
                new ObjectParameter("C_BENEF_RELATION_TYPE_1", c_BENEF_RELATION_TYPE_1) :
                new ObjectParameter("C_BENEF_RELATION_TYPE_1", typeof(string));
    
            var c_BENEF_NAME_2Parameter = c_BENEF_NAME_2 != null ?
                new ObjectParameter("C_BENEF_NAME_2", c_BENEF_NAME_2) :
                new ObjectParameter("C_BENEF_NAME_2", typeof(string));
    
            var c_BENEF_SEX_2Parameter = c_BENEF_SEX_2 != null ?
                new ObjectParameter("C_BENEF_SEX_2", c_BENEF_SEX_2) :
                new ObjectParameter("C_BENEF_SEX_2", typeof(string));
    
            var d_BENEF_DOB_2Parameter = d_BENEF_DOB_2.HasValue ?
                new ObjectParameter("D_BENEF_DOB_2", d_BENEF_DOB_2) :
                new ObjectParameter("D_BENEF_DOB_2", typeof(System.DateTime));
    
            var n_BENEF_SHARE_2Parameter = n_BENEF_SHARE_2.HasValue ?
                new ObjectParameter("N_BENEF_SHARE_2", n_BENEF_SHARE_2) :
                new ObjectParameter("N_BENEF_SHARE_2", typeof(double));
    
            var c_BENEF_RELATION_TYPE_2Parameter = c_BENEF_RELATION_TYPE_2 != null ?
                new ObjectParameter("C_BENEF_RELATION_TYPE_2", c_BENEF_RELATION_TYPE_2) :
                new ObjectParameter("C_BENEF_RELATION_TYPE_2", typeof(string));
    
            var c_BENEF_NAME_3Parameter = c_BENEF_NAME_3 != null ?
                new ObjectParameter("C_BENEF_NAME_3", c_BENEF_NAME_3) :
                new ObjectParameter("C_BENEF_NAME_3", typeof(string));
    
            var c_BENEF_SEX_3Parameter = c_BENEF_SEX_3 != null ?
                new ObjectParameter("C_BENEF_SEX_3", c_BENEF_SEX_3) :
                new ObjectParameter("C_BENEF_SEX_3", typeof(string));
    
            var d_BENEF_DOB_3Parameter = d_BENEF_DOB_3.HasValue ?
                new ObjectParameter("D_BENEF_DOB_3", d_BENEF_DOB_3) :
                new ObjectParameter("D_BENEF_DOB_3", typeof(System.DateTime));
    
            var n_BENEF_SHARE_3Parameter = n_BENEF_SHARE_3.HasValue ?
                new ObjectParameter("N_BENEF_SHARE_3", n_BENEF_SHARE_3) :
                new ObjectParameter("N_BENEF_SHARE_3", typeof(double));
    
            var c_BENEF_RELATION_TYPE_3Parameter = c_BENEF_RELATION_TYPE_3 != null ?
                new ObjectParameter("C_BENEF_RELATION_TYPE_3", c_BENEF_RELATION_TYPE_3) :
                new ObjectParameter("C_BENEF_RELATION_TYPE_3", typeof(string));
    
            var c_BENEF_NAME_4Parameter = c_BENEF_NAME_4 != null ?
                new ObjectParameter("C_BENEF_NAME_4", c_BENEF_NAME_4) :
                new ObjectParameter("C_BENEF_NAME_4", typeof(string));
    
            var c_BENEF_SEX_4Parameter = c_BENEF_SEX_4 != null ?
                new ObjectParameter("C_BENEF_SEX_4", c_BENEF_SEX_4) :
                new ObjectParameter("C_BENEF_SEX_4", typeof(string));
    
            var d_BENEF_DOB_4Parameter = d_BENEF_DOB_4.HasValue ?
                new ObjectParameter("D_BENEF_DOB_4", d_BENEF_DOB_4) :
                new ObjectParameter("D_BENEF_DOB_4", typeof(System.DateTime));
    
            var n_BENEF_SHARE_4Parameter = n_BENEF_SHARE_4.HasValue ?
                new ObjectParameter("N_BENEF_SHARE_4", n_BENEF_SHARE_4) :
                new ObjectParameter("N_BENEF_SHARE_4", typeof(double));
    
            var c_BENEF_RELATION_TYPE_4Parameter = c_BENEF_RELATION_TYPE_4 != null ?
                new ObjectParameter("C_BENEF_RELATION_TYPE_4", c_BENEF_RELATION_TYPE_4) :
                new ObjectParameter("C_BENEF_RELATION_TYPE_4", typeof(string));
    
            var n_STAGING_DTL_IDParameter = n_STAGING_DTL_ID.HasValue ?
                new ObjectParameter("N_STAGING_DTL_ID", n_STAGING_DTL_ID) :
                new ObjectParameter("N_STAGING_DTL_ID", typeof(int));
    
            var n_USER_IDParameter = n_USER_ID.HasValue ?
                new ObjectParameter("N_USER_ID", n_USER_ID) :
                new ObjectParameter("N_USER_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CREATE_POLICY", n_PRODUCT_IDParameter, c_NO_SPAJParameter, c_AGENT_CODEParameter, n_HOLDER_CUSTOMER_IDParameter, n_INSURED_CUSTOMER_IDParameter, c_HOLDER_INSURED_RELATION_TYPEParameter, d_START_DATEParameter, d_MATURE_DATEParameter, d_FREE_LOOK_LAST_DAYParameter, n_CUST_BANK_IDParameter, c_BENEF_NAME_1Parameter, c_BENEF_SEX_1Parameter, d_BENEF_DOB_1Parameter, n_BENEF_SHARE_1Parameter, c_BENEF_RELATION_TYPE_1Parameter, c_BENEF_NAME_2Parameter, c_BENEF_SEX_2Parameter, d_BENEF_DOB_2Parameter, n_BENEF_SHARE_2Parameter, c_BENEF_RELATION_TYPE_2Parameter, c_BENEF_NAME_3Parameter, c_BENEF_SEX_3Parameter, d_BENEF_DOB_3Parameter, n_BENEF_SHARE_3Parameter, c_BENEF_RELATION_TYPE_3Parameter, c_BENEF_NAME_4Parameter, c_BENEF_SEX_4Parameter, d_BENEF_DOB_4Parameter, n_BENEF_SHARE_4Parameter, c_BENEF_RELATION_TYPE_4Parameter, n_STAGING_DTL_IDParameter, n_USER_IDParameter, n_POLICY_ID, outErrMsg);
        }
    
        public virtual int SP_EMAIL_DATA_CLAIM()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_EMAIL_DATA_CLAIM");
        }
    
        public virtual int SP_EMAIL_DATA_PRODUKSI()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_EMAIL_DATA_PRODUKSI");
        }
    
        public virtual int SP_LIST_PRODUKSI_INVESTA(Nullable<System.DateTime> curDate)
        {
            var curDateParameter = curDate.HasValue ?
                new ObjectParameter("CurDate", curDate) :
                new ObjectParameter("CurDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_LIST_PRODUKSI_INVESTA", curDateParameter);
        }
    
        public virtual int SP_LIST_PRODUKSI_IPP(Nullable<System.DateTime> curDate)
        {
            var curDateParameter = curDate.HasValue ?
                new ObjectParameter("CurDate", curDate) :
                new ObjectParameter("CurDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_LIST_PRODUKSI_IPP", curDateParameter);
        }
    
        public virtual int SP_LIST_PRODUKSI_JIWA(Nullable<System.DateTime> curDate)
        {
            var curDateParameter = curDate.HasValue ?
                new ObjectParameter("CurDate", curDate) :
                new ObjectParameter("CurDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_LIST_PRODUKSI_JIWA", curDateParameter);
        }
    
        public virtual int SP_LIST_PRODUKSI_TRD(Nullable<System.DateTime> curDate)
        {
            var curDateParameter = curDate.HasValue ?
                new ObjectParameter("CurDate", curDate) :
                new ObjectParameter("CurDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_LIST_PRODUKSI_TRD", curDateParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_NEWAGE(Nullable<int> id, string dob)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var dobParameter = dob != null ?
                new ObjectParameter("Dob", dob) :
                new ObjectParameter("Dob", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_NEWAGE", idParameter, dobParameter);
        }
    
        public virtual int SP_PROCCESS_LAPSE()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_PROCCESS_LAPSE");
        }
    
        public virtual ObjectResult<SP_PROCESS_CONFIRMED_DATA_Result> SP_PROCESS_CONFIRMED_DATA(Nullable<int> p_N_STAGING_HDR_ID, Nullable<int> n_USER_ID)
        {
            var p_N_STAGING_HDR_IDParameter = p_N_STAGING_HDR_ID.HasValue ?
                new ObjectParameter("P_N_STAGING_HDR_ID", p_N_STAGING_HDR_ID) :
                new ObjectParameter("P_N_STAGING_HDR_ID", typeof(int));
    
            var n_USER_IDParameter = n_USER_ID.HasValue ?
                new ObjectParameter("N_USER_ID", n_USER_ID) :
                new ObjectParameter("N_USER_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_PROCESS_CONFIRMED_DATA_Result>("SP_PROCESS_CONFIRMED_DATA", p_N_STAGING_HDR_IDParameter, n_USER_IDParameter);
        }
    
        public virtual ObjectResult<SP_PRODUCTION_SUMMARY_Result> SP_PRODUCTION_SUMMARY()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_PRODUCTION_SUMMARY_Result>("SP_PRODUCTION_SUMMARY");
        }
    
        public virtual int SP_UPLOAD_CUST_VALIDATE(Nullable<int> p_N_STAGING_HDR_ID, Nullable<System.DateTime> p_D_POLICY_EFFECTIVE_DATE, Nullable<int> n_USER_ID)
        {
            var p_N_STAGING_HDR_IDParameter = p_N_STAGING_HDR_ID.HasValue ?
                new ObjectParameter("P_N_STAGING_HDR_ID", p_N_STAGING_HDR_ID) :
                new ObjectParameter("P_N_STAGING_HDR_ID", typeof(int));
    
            var p_D_POLICY_EFFECTIVE_DATEParameter = p_D_POLICY_EFFECTIVE_DATE.HasValue ?
                new ObjectParameter("P_D_POLICY_EFFECTIVE_DATE", p_D_POLICY_EFFECTIVE_DATE) :
                new ObjectParameter("P_D_POLICY_EFFECTIVE_DATE", typeof(System.DateTime));
    
            var n_USER_IDParameter = n_USER_ID.HasValue ?
                new ObjectParameter("N_USER_ID", n_USER_ID) :
                new ObjectParameter("N_USER_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UPLOAD_CUST_VALIDATE", p_N_STAGING_HDR_IDParameter, p_D_POLICY_EFFECTIVE_DATEParameter, n_USER_IDParameter);
        }
    
        public virtual int SP_UPLOAD_PAY_RECON(Nullable<long> id, Nullable<int> user)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(long));
    
            var userParameter = user.HasValue ?
                new ObjectParameter("user", user) :
                new ObjectParameter("user", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UPLOAD_PAY_RECON", idParameter, userParameter);
        }
    
        public virtual int TestProc()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TestProc");
        }
    
        public virtual int TestProc2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TestProc2");
        }
    
        public virtual int usp_GetErrorInfo(ObjectParameter outMessage)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_GetErrorInfo", outMessage);
        }
    }
}
