//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMigrationConsoleTools.DataModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ILIASEntities : DbContext
    {
        public ILIASEntities()
            : base("name=ILIASEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADDRESS> ADDRESS { get; set; }
        public virtual DbSet<APPLICATION> APPLICATION { get; set; }
        public virtual DbSet<APPREL> APPREL { get; set; }
        public virtual DbSet<CLIENT> CLIENT { get; set; }
        public virtual DbSet<BANK> BANK { get; set; }
        public virtual DbSet<View_BankAccount> View_BankAccount { get; set; }
        public virtual DbSet<BENEFICIARY> BENEFICIARY { get; set; }
    }
}
