//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMigrationConsoleTools.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewClient
    {
        public string client_id_temp { get; set; }
        public string policy_no { get; set; }
        public string policy_product { get; set; }
        public string ppOrttOrbf { get; set; }
        public string client_no { get; set; }
        public string salutation { get; set; }
        public string client_name { get; set; }
        public string birth_place { get; set; }
        public System.DateTime birth_date { get; set; }
        public string gender_code { get; set; }
        public string marital_status_code { get; set; }
        public string occupation_code { get; set; }
        public string category_code { get; set; }
        public string position_code { get; set; }
        public string education_code { get; set; }
        public string client_type_code { get; set; }
        public string religion_code { get; set; }
        public string smoker_status { get; set; }
        public Nullable<decimal> cigarete_perday { get; set; }
        public string residence_address1 { get; set; }
        public string residence_address2 { get; set; }
        public string residence_phone_no { get; set; }
        public string residence_fax { get; set; }
        public string residence_city { get; set; }
        public string residence_postal_code { get; set; }
        public string residence_province_code { get; set; }
        public string office_address1 { get; set; }
        public string office_address2 { get; set; }
        public string office_phone_no { get; set; }
        public string office_fax { get; set; }
        public string office_city { get; set; }
        public string office_province_code { get; set; }
        public string office_postal_code { get; set; }
        public string mail_address1 { get; set; }
        public string mail_address2 { get; set; }
        public string mail_city { get; set; }
        public string mail_province_code { get; set; }
        public string mail_postal_code { get; set; }
        public string bi_code { get; set; }
        public string bank_account_no { get; set; }
        public string bank_branch { get; set; }
        public string bank_city { get; set; }
        public string account_holder { get; set; }
        public string account_holder_relation_code { get; set; }
        public string mobile_phone { get; set; }
        public string email { get; set; }
        public string id_type_code { get; set; }
        public string no_id { get; set; }
        public Nullable<System.DateTime> id_issue_date { get; set; }
        public Nullable<System.DateTime> id_expire_date { get; set; }
        public Nullable<decimal> height { get; set; }
        public Nullable<decimal> weight { get; set; }
        public Nullable<decimal> monthly_cost { get; set; }
        public string client_status { get; set; }
        public string npwp { get; set; }
        public string npwp_name { get; set; }
        public string npwp_address { get; set; }
        public string front_title { get; set; }
        public string back_title { get; set; }
        public string mother_name { get; set; }
        public Nullable<System.DateTime> mother_birth_date { get; set; }
    }
}
