//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMigrationConsoleTools.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class PolisIPP
    {
        public Nullable<int> Day_SPAJ { get; set; }
        public Nullable<int> Month_SPAJ { get; set; }
        public Nullable<int> Year_SPAJ { get; set; }
        public string No_SPAJ { get; set; }
        public string No_Polis { get; set; }
        public Nullable<int> Day_Underwriting { get; set; }
        public Nullable<int> Month_Underwriting { get; set; }
        public Nullable<int> Year_Underwriting { get; set; }
        public string Policyholder_Name { get; set; }
        public string Policyholder_Korespondensi { get; set; }
        public string Policyholder_Kel { get; set; }
        public string Policyholder_Kec { get; set; }
        public string Policyholder_City { get; set; }
        public string Policyholder_KodePos { get; set; }
        public string Policyholder_Telp { get; set; }
        public string Policyholder_HP { get; set; }
        public string Policyholder_Email { get; set; }
        public string Policyholder_Kewarganegaraan { get; set; }
        public string Policyholder_Sex { get; set; }
        public Nullable<int> Policyholder_DayLahir { get; set; }
        public Nullable<int> Policyholder_MonthLahir { get; set; }
        public Nullable<int> Policyholder_YearLahir { get; set; }
        public string Policyholder_Status { get; set; }
        public string Policyholder_NPWP { get; set; }
        public string Policyholder_IDtype { get; set; }
        public string Policyholder_NoID { get; set; }
        public string Policyholder_Pekerjaan { get; set; }
        public string Policyholder_Perusahaan { get; set; }
        public string Policyholder_AlamatPerusahaan { get; set; }
        public string Policyholder_Jabatan { get; set; }
        public string Policyholder_UrainPekerjaan { get; set; }
        public string Insured_Name { get; set; }
        public string Insured_Korespondensi { get; set; }
        public string Insured_Kel { get; set; }
        public string Insured_Kec { get; set; }
        public string Insured_City { get; set; }
        public string Insured_KodePos { get; set; }
        public string Insured_Telp { get; set; }
        public string Insured_HP { get; set; }
        public string Insured_Email { get; set; }
        public string Insured_Kewarganegaraan { get; set; }
        public string Insured_Sex { get; set; }
        public Nullable<int> Insured_DayLahir { get; set; }
        public Nullable<int> Insured_MonthLahir { get; set; }
        public Nullable<int> Insured_YearLahir { get; set; }
        public string Insured_Status { get; set; }
        public string Insured_NPWP { get; set; }
        public string Insured_IDType { get; set; }
        public string Insured_NoID { get; set; }
        public string Insured_Pekerjaan { get; set; }
        public string Insured_Perusahaan { get; set; }
        public string Insured_AlamatPerusahaan { get; set; }
        public string Insured_Jabatan { get; set; }
        public string Insured_UraianPekerjaan { get; set; }
        public string Insured_Hub { get; set; }
        public string Insured_AlasanMengasuransikan { get; set; }
        public string Tujuan_Asuransi { get; set; }
        public string Insured_JelaskanTujuan { get; set; }
        public string Sumber_Penghasilan { get; set; }
        public string Nominal_Penghasilan { get; set; }
        public string Aset_BadanHukum { get; set; }
        public string TujuanAsuransi_BadanHukum { get; set; }
        public string Pendapatan_BadanHukum { get; set; }
        public string JelaskanAsuransi_BadanHukum { get; set; }
        public Nullable<decimal> Uang_Pertanggungan { get; set; }
        public Nullable<decimal> PremiSekaligus { get; set; }
        public Nullable<int> MasaAsuransi { get; set; }
        public Nullable<decimal> TingkatBungaInvestasi { get; set; }
        public string PeriodeManfaatInvestasi { get; set; }
        public string Policyholder_NamaBank { get; set; }
        public string Policyholder_CabangBank { get; set; }
        public string Policyholder_NamaPemilik { get; set; }
        public string Policyholder_NoRekPemilik { get; set; }
        public string PihakYgDitunjuk_Nama1 { get; set; }
        public string PihakYgDitunjuk_Hub1 { get; set; }
        public string PihakYgDitunjuk_Sex1 { get; set; }
        public Nullable<int> PihakYgDitunjuk_Day1 { get; set; }
        public Nullable<int> PihakYgDitunjuk_Month1 { get; set; }
        public Nullable<int> PihakYgDitunjuk_Year1 { get; set; }
        public Nullable<decimal> PihakYgDitunjuk_Benefit1 { get; set; }
        public string PihakYgDitunjuk_Nama2 { get; set; }
        public string PihakYgDitunjuk_Hub2 { get; set; }
        public string PihakYgDitunjuk_Sex2 { get; set; }
        public Nullable<int> PihakYgDitunjuk_Day2 { get; set; }
        public Nullable<int> PihakYgDitunjuk_Month2 { get; set; }
        public Nullable<int> PihakYgDitunjuk_Year2 { get; set; }
        public Nullable<decimal> PihakYgDitunjuk_Benefit2 { get; set; }
        public string PihakYgDitunjuk_Nama3 { get; set; }
        public string PihakYgDitunjuk_Hub3 { get; set; }
        public string PihakYgDitunjuk_Sex3 { get; set; }
        public Nullable<int> PihakYgDitunjuk_Day3 { get; set; }
        public Nullable<int> PihakYgDitunjuk_Month3 { get; set; }
        public Nullable<int> PihakYgDitunjuk_Year3 { get; set; }
        public Nullable<decimal> PihakYgDitunjuk_Benefit3 { get; set; }
        public string PihakYgDitunjuk_Nama4 { get; set; }
        public string PihakYgDitunjuk_Hub4 { get; set; }
        public string PihakYgDitunjuk_Sex4 { get; set; }
        public Nullable<int> PihakYgDitunjuk_Day4 { get; set; }
        public Nullable<int> PihakYgDitunjuk_Month4 { get; set; }
        public Nullable<int> PihakYgDitunjuk_Year4 { get; set; }
        public Nullable<decimal> PihakYgDitunjuk_Benefit4 { get; set; }
        public string PihakYgDitunjuk_Nama5 { get; set; }
        public string PihakYgDitunjuk_Hub5 { get; set; }
        public string PihakYgDitunjuk_Sex5 { get; set; }
        public Nullable<int> PihakYgDitunjuk_Day5 { get; set; }
        public Nullable<int> PihakYgDitunjuk_Month5 { get; set; }
        public Nullable<int> PihakYgDitunjuk_Year5 { get; set; }
        public Nullable<decimal> PihakYgDitunjuk_Benefit5 { get; set; }
        public string PihakYgDitunjuk_Nama6 { get; set; }
        public string PihakYgDitunjuk_Hub6 { get; set; }
        public string PihakYgDitunjuk_Sex6 { get; set; }
        public Nullable<int> PihakYgDitunjuk_Day6 { get; set; }
        public Nullable<int> PihakYgDitunjuk_Month6 { get; set; }
        public Nullable<int> PihakYgDitunjuk_Year6 { get; set; }
        public Nullable<decimal> PihakYgDitunjuk_Benefit6 { get; set; }
        public string PihakYgDitunjuk_Nama7 { get; set; }
        public string PihakYgDitunjuk_Hub7 { get; set; }
        public string PihakYgDitunjuk_Sex7 { get; set; }
        public Nullable<int> PihakYgDitunjuk_Day7 { get; set; }
        public Nullable<int> PihakYgDitunjuk_Month7 { get; set; }
        public Nullable<int> PihakYgDitunjuk_Year7 { get; set; }
        public Nullable<decimal> PihakYgDitunjuk_Benefit7 { get; set; }
        public Nullable<int> PernyataanPenutup_YaTidak1 { get; set; }
        public string PernyataanPenutup_1 { get; set; }
        public Nullable<int> PernyataanPenutup_YaTidak2 { get; set; }
        public string PernyataanPenutup_2 { get; set; }
        public Nullable<int> PernyataanPenutup_YaTidak3 { get; set; }
        public string PernyataanPenutup_3 { get; set; }
        public string Tempat_dittd { get; set; }
        public Nullable<int> Day_ttd { get; set; }
        public Nullable<int> Month_ttd { get; set; }
        public Nullable<int> Year_ttd { get; set; }
        public string Penutup_Nama { get; set; }
        public string Penutup_Kode { get; set; }
        public string Penutup_Cabang { get; set; }
        public string Penutup_Telp { get; set; }
        public string Penutup_HP { get; set; }
        public Nullable<int> Keputusan_Underwriting { get; set; }
        public string Note_Underwriting { get; set; }
        public Nullable<int> Policyholder_Age { get; set; }
        public Nullable<int> Insured_Age { get; set; }
        public Nullable<int> MGI { get; set; }
        public Nullable<int> Issue_Day { get; set; }
        public string Issue_Month { get; set; }
        public Nullable<int> Issue_Year { get; set; }
        public Nullable<System.DateTime> Tanggal_Lapse { get; set; }
        public string Status_Inforce { get; set; }
        public Nullable<System.DateTime> Tgl_Issued { get; set; }
        public string Create_UserID { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public string Update_UserID { get; set; }
        public Nullable<System.DateTime> Update_Date { get; set; }
    }
}
