//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMigrationConsoleTools.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblUserPPResponse
    {
        public int IdToken { get; set; }
        public string NoPolis { get; set; }
        public string ResponseId { get; set; }
        public string ResponseDesc { get; set; }
        public Nullable<bool> MoveFromIPPToIVL { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public Nullable<System.DateTime> Modify_Date { get; set; }
    
        public virtual TblUserTokenPP TblUserTokenPP { get; set; }
    }
}
