//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMigrationConsoleTools.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_BankAccount
    {
        public int ROW_ID { get; set; }
        public string APPLI_NUM { get; set; }
        public string NAME { get; set; }
        public string TITLE { get; set; }
        public string CURR { get; set; }
        public string ACCNUMBER { get; set; }
        public string BANKNAME { get; set; }
        public string BRANCH { get; set; }
        public string CITY { get; set; }
    }
}
