//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMigrationConsoleTools.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_jiwa_db
    {
        public System.DateTime tgltrans { get; set; }
        public string policy_id { get; set; }
        public string policy_holder_name { get; set; }
        public string product { get; set; }
        public System.DateTime tglissued { get; set; }
        public System.DateTime tgleffective { get; set; }
        public string freq { get; set; }
        public string curr { get; set; }
        public int UP { get; set; }
        public Nullable<double> premi { get; set; }
        public int EM { get; set; }
        public Nullable<double> total { get; set; }
        public string DC { get; set; }
        public string title { get; set; }
        public int pic { get; set; }
        public string picname { get; set; }
        public int years { get; set; }
        public int unit { get; set; }
        public string unit_name { get; set; }
        public string status { get; set; }
        public System.DateTime tglfreelook { get; set; }
    }
}
