//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMigrationWebTools.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvestaEOM
    {
        public string SPAJ { get; set; }
        public Nullable<decimal> Unit_Balance { get; set; }
        public Nullable<System.DateTime> Eff_Date { get; set; }
        public Nullable<System.DateTime> LastEOM { get; set; }
        public Nullable<System.DateTime> NextEOM { get; set; }
    }
}
