//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMigrationWebTools.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Investa_CashBack
    {
        public string No_SPAJ { get; set; }
        public string No_CashReward { get; set; }
        public string No_Polis { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> MPI { get; set; }
        public string Nama_PP { get; set; }
        public Nullable<decimal> Rate_Cash { get; set; }
        public Nullable<decimal> Total_Premi { get; set; }
        public Nullable<decimal> Cash_Reward { get; set; }
        public string Create_UserId { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public string Modify_UserId { get; set; }
        public Nullable<System.DateTime> Modify_Date { get; set; }
    }
}
