//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMigrationWebTools.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPPCancel
    {
        public string No_SPAJ { get; set; }
        public string No_Polis { get; set; }
        public Nullable<System.DateTime> Cancel_Date { get; set; }
        public string Cancel_Desc { get; set; }
        public string Create_UserId { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public string Modify_UserID { get; set; }
        public Nullable<System.DateTime> Modify_Date { get; set; }
    }
}
