//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMigrationWebTools.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class nb_application_insured
    {
        public string application_no { get; set; }
        public string insured_no { get; set; }
        public int start_age { get; set; }
        public decimal insurance_period_year { get; set; }
        public Nullable<decimal> insurance_period_month { get; set; }
        public string insurable_code { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime end_date { get; set; }
        public int order_no { get; set; }
        public string active_status { get; set; }
    }
}
