//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMigrationWebTools.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class nb_application_premium_history
    {
        public string application_no { get; set; }
        public System.DateTime booked_date { get; set; }
        public Nullable<int> period { get; set; }
        public System.DateTime period_date { get; set; }
        public System.DateTime due_date { get; set; }
        public decimal rp_amount { get; set; }
        public decimal stu_amount { get; set; }
        public decimal utu_amount { get; set; }
        public decimal billing_amount { get; set; }
        public decimal collection_amount { get; set; }
        public Nullable<decimal> exchange_rate { get; set; }
        public string recon_status { get; set; }
        public System.DateTime recon_date { get; set; }
        public string billing_id_ref { get; set; }
        public string collection_id_ref { get; set; }
    }
}
