//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMigrationWebTools.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PolisResponse
    {
        public string SPAJ { get; set; }
        public string Polis { get; set; }
        public string Product { get; set; }
        public Nullable<System.DateTime> Due_Date { get; set; }
        public string Response { get; set; }
        public string Description { get; set; }
        public string PR_NUM { get; set; }
        public string PR_Sts { get; set; }
        public string Create_UserId { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public string Modify_UserId { get; set; }
        public Nullable<System.DateTime> Modify_Date { get; set; }
    }
}
