//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMigrationWebTools.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ps_alteration_withdrawal
    {
        public string alteration_id { get; set; }
        public System.DateTime trans_date { get; set; }
        public string withdrawal_apply { get; set; }
        public Nullable<decimal> trans_amt { get; set; }
        public Nullable<decimal> trans_unit { get; set; }
        public Nullable<System.DateTime> pricing_date { get; set; }
        public string posting_status { get; set; }
        public Nullable<System.DateTime> posting_date { get; set; }
        public Nullable<System.DateTime> settle_date { get; set; }
        public string current_fundhouse_code { get; set; }
        public Nullable<decimal> withdrawal_fee { get; set; }
        public Nullable<decimal> refund_fee { get; set; }
        public Nullable<decimal> total_collection_amt { get; set; }
        public Nullable<decimal> total_account_value { get; set; }
        public Nullable<decimal> total_taxable_amt { get; set; }
        public Nullable<decimal> taxable_amt { get; set; }
        public Nullable<decimal> tax_amt { get; set; }
        public Nullable<decimal> fund_withdrawn { get; set; }
        public string voucher_reff_id { get; set; }
        public Nullable<decimal> neutralize_amount { get; set; }
    }
}
