//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMigrationWebTools.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ps_alteration_fund_allocation_detail
    {
        public string alteration_id { get; set; }
        public string fund_code_from { get; set; }
        public string fund_code_to { get; set; }
        public Nullable<decimal> alt_fund_pct { get; set; }
        public Nullable<decimal> alt_fund_amt { get; set; }
        public Nullable<decimal> alt_unit_amt { get; set; }
    }
}
