//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMigrationWebTools.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ps_fund_transaction_history
    {
        public string transaction_id { get; set; }
        public string fund_code { get; set; }
        public string transaction_type_code { get; set; }
        public System.DateTime transaction_date { get; set; }
        public Nullable<decimal> fund_pct { get; set; }
        public decimal fund_amt { get; set; }
        public System.DateTime confirm_date { get; set; }
        public Nullable<decimal> collection_amt { get; set; }
        public string investible_status { get; set; }
        public Nullable<decimal> admfee_amt { get; set; }
        public decimal investible_amt { get; set; }
        public Nullable<System.DateTime> pricing_date { get; set; }
        public System.DateTime posting_date { get; set; }
        public string posting_status { get; set; }
        public decimal unit_amt { get; set; }
        public decimal begin_balance { get; set; }
        public decimal final_balance { get; set; }
        public string alteration_id { get; set; }
        public string application_no { get; set; }
        public string module_source { get; set; }
        public string collection_id { get; set; }
        public System.DateTime real_pricing_date { get; set; }
        public Nullable<decimal> pnl_amt { get; set; }
        public Nullable<decimal> pnl_unit { get; set; }
    }
}
