//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMigrationWebTools.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblLabelNew
    {
        public string No_Spaj { get; set; }
        public string No_Polis { get; set; }
        public string PolicyHolder { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string No_Telp { get; set; }
        public string Product { get; set; }
        public string ProductName { get; set; }
        public string No_Agen { get; set; }
        public string AgenName { get; set; }
        public string AgenBranch { get; set; }
        public Nullable<System.DateTime> Tgl_Spaj { get; set; }
        public Nullable<System.DateTime> Tgl_Aksep { get; set; }
        public Nullable<System.DateTime> Tgl_Kirim { get; set; }
        public Nullable<System.DateTime> Tgl_Terima { get; set; }
        public string Sts { get; set; }
        public string Keterangan { get; set; }
        public string Create_UserId { get; set; }
        public Nullable<System.DateTime> Create_date { get; set; }
        public string Modify_UserId { get; set; }
        public Nullable<System.DateTime> Modify_Date { get; set; }
    }
}
