//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMigrationWebTools.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblRole
    {
        public string RoleId { get; set; }
        public string FrmName { get; set; }
        public string Object { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
