//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMigrationWebTools.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_aum_ios
    {
        public string produk { get; set; }
        public string periode { get; set; }
        public string polis { get; set; }
        public string nama_pp { get; set; }
        public Nullable<decimal> premi { get; set; }
        public Nullable<System.DateTime> tgl_transaksi { get; set; }
        public string polisbaru { get; set; }
        public decimal premibaru { get; set; }
        public System.DateTime tgl_trx_baru { get; set; }
        public string keterangan { get; set; }
        public Nullable<decimal> selisih { get; set; }
        public string agen { get; set; }
    }
}
