//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMigrationWebTools.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_endors_ivl
    {
        public string spaj { get; set; }
        public string polis { get; set; }
        public Nullable<System.DateTime> endorsement_date { get; set; }
        public string endorsement_id { get; set; }
        public Nullable<int> mpi { get; set; }
        public string endorsement_remarks { get; set; }
    }
}
