//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMigrationWebTools.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_polis
    {
        public string NO_SPAJ { get; set; }
        public string PRODUCT { get; set; }
        public string KODE_PRODUCT { get; set; }
        public string NO_POLIS { get; set; }
        public string PEMEGANG_POLIS { get; set; }
        public string NAMA_TERTANGGUNG { get; set; }
        public Nullable<decimal> TOTAL_PREMI { get; set; }
        public Nullable<System.DateTime> EFFECTIVE_POLIS { get; set; }
        public Nullable<int> MASA_PROYEKSI { get; set; }
        public string CARA_PENARIKAN_DANA { get; set; }
        public Nullable<System.DateTime> TANGGAL_JATUH_TEMPO { get; set; }
        public string NO_REK_PP { get; set; }
        public string NAMA_BANK_PP { get; set; }
        public string CABANG_REK_PP { get; set; }
        public string ATAS_NAMA_PP { get; set; }
    }
}
